### ISSUE TITLE
how to set max-height in ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by dyh333** [zefoy/ngx-perfect-scrollbar#103]
hi, I want set a max-height for div, but not work, but try in pure perfect-scroll is ok.
this is [pure perfect-scroll](https://jsfiddle.net/dyh333/hufuen52/)
this is [ngx-perfect-scrollbar](https://plnkr.co/edit/n7rbs6HDJG7MUtYszjAL?p=preview)

![image](https://user-images.githubusercontent.com/1221313/32204739-fae7ec7c-be25-11e7-9323-434b571df73a.png)
this is what I update

**Comment by sconix** [comment]
You need to set the max-height for the ps class via css rules. Or you can use the directive when you can set the max-height style directly in the styles. 

I will add a max-height: inherit for the ps class for next release so then one can set the style directly in the component style like you have tried.

**Comment by sconix** [comment]
With 4.9.2 version onwards the max-height set on the component should have effect.
