### ISSUE TITLE
Angular 5 - no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by andrefvicente** [zefoy/ngx-perfect-scrollbar#105]
Hi,

After the update to angular 5. We found the following error:

ERROR in ..../node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts (1,31): Module '".../node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

Thanks

**Comment by sconix** [comment]
With Angular 5 you need to use the 5.x version of this library, more specifically use 5.0.0-7 version. The latest pre-release is buggy and I will make new one as soon as new release of perfect-scrollbar is out. I will release version 5.0.0 officially when Angular 5 is out.

**Comment by lexsalg** [comment]
Angular 5 is now official
https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

**Comment by lexsalg** [comment]
Replace OpaqueTokens with InjectionTokens.

**Comment by sconix** [comment]
It has been already replaced as said there is a pre-release for Angular 5 (version 5.0.0-7). New "official" release comes when also perfect-scrollbar release is out which fixes problems that are preventing me to update to ps 1.x.
