### ISSUE TITLE
Issue with Angular5

### ISSUE THREAD

**Issue by mafoss** [zefoy/ngx-perfect-scrollbar#106]
Since Angular v5.0.0 was released and OpaqueToken is now deprecated, ngx-perfect-scrollbar cannot be used with Angular 5.0.0.

From the Angular Changelog: 

>Breaking Changes 
>core: OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.

**Comment by mafoss** [comment]
Sorry, i just saw that you've already committed some changes regarding this issue. 
Thank you for your great work!

**Comment by sconix** [comment]
There is a pre-release 5.0.0-7 out that works with Angular 5, new official release coming once perfect-scrollbar is updated.
