### ISSUE TITLE
npm version 4.8.4

### ISSUE THREAD

**Issue by kourosko** [zefoy/ngx-perfect-scrollbar#107]
Hi I see the changes in your code for Angular 5 but for some reason with npm i get version 4.8.4 with the old code..

**Comment by sconix** [comment]
I want to release the version 5 with perfects-scrollbar 1.x, but to do that I need to wait for new release of PS 1.x to get the fixes I need. The fixes has been already merged but there has not been yet made a new release. So as soon as new version of PS is out I will release 5.0.0.

**Comment by sconix** [comment]
There is now new pre-release 5.0.0-9 which is build using Angular 5 and is fully compatible with it. It also uses perfect-scrollbar 1.x. This is a huge update so check the releases page for changes.
