### ISSUE TITLE
Need to clear timeouts on destroy

### ISSUE THREAD

**Issue by BONDRV** [zefoy/ngx-perfect-scrollbar#110]
Function "removeScrollingClass" uses setTimeout. But if you destroing perfectScrollbar instance by using method "destroy" timeouts don't stops.
This creates error:

**Uncaught TypeError: Cannot read property 'classList' of null**

in function:
```
function removeScrollingClass(i, x) {
  scrollingClassTimeout[x] = setTimeout(
    function () { return i.element.classList.remove(cls.state.scrolling(x)); },
    i.settings.scrollingThreshold
  );
}
```

**Comment by sconix** [comment]
Thanks, will fix for next release. Actually that code is not used in the latest release anymore since the next 1.x perfect-scrollbar handles the scrolling class.
