### ISSUE TITLE
Scrollbar shows up on emulator but not on device

### ISSUE THREAD

**Issue by deepansha-tiwari** [zefoy/ngx-perfect-scrollbar#111]
The scrollbar shows up on the emulator running Android 7.1.1 but not on the device running Android 6.0.1

Have tried both: "angular2-perfect-scrollbar": "^2.0.6" and "ngx-perfect-scrollbar": "^4.8.4"

`<div *ngSwitchCase="'abcdescription'" [hidden]="!isabcType" (click)="getabcDescription()">
       
        <div [hidden]="hasTask"><h3>No abc found</h3></div>
        
        <perfect-scrollbar class="container">
          <div class="content" style="height:412px;">
    <pre style="white-space:pre-wrap;"><h4 [innerHTML]="abc" class="abcclass"></h4></pre>
  </div>
</perfect-scrollbar> `

**Comment by sconix** [comment]
Do you mean that you don't see the scrollbars on mobile when scrolling?

Have you tried the directive instead of the component? It should not have an effect, but worth to try to give me some idea what could be wrong. We don't have any issues in Android.

**Comment by deepansha-tiwari** [comment]
Yes, the scrollbar doesn't show up when I run on the mobile device but it does show up on the emulator. I tried the directive and that didn't work on either of them.

**Comment by sconix** [comment]
I suspect that you have to have some sort of style issue. Without way to reproduce hard to say for sure. You should try the next release (4.9.2) which is out soon. It uses perfect-scrollbar 1.x and many things have changed from 0.8 version.

**Comment by sconix** [comment]
I just released 4.9.2 so could you try that. If you still have problems then could you check the perfect-scrollbar issues if this kind of issue is known there. This wrapper should not be the reason specially when using directive. 

If you are still out of luck perhaps you could make some test page? Since we use this library in our app and have no problems in Android nor iOS.

**Comment by deepansha-tiwari** [comment]
4.9.2 worked like a charm! Thanks!
