### ISSUE TITLE
After reload two scroll bars

### ISSUE THREAD

**Issue by armangevorgyan** [zefoy/ngx-perfect-scrollbar#112]
before reload https://gyazo.com/10183310bdd8bae364a7d3a7cc36437c
after reload https://gyazo.com/856b3224d631ac880d85d034fb406cad;
If i call update() after refresh page scroll works normal, but i can't call update() for [perfectScrollbar] directive

**Comment by sconix** [comment]
To me that looks like a styling problem. I.e. for some reason your scroll area gets bigger than its parent. Not sure why the update call fixes the situation though. I don't quite follow that what you mean that if you call update() it works, but how do you call it if you can't call it? :)

You can call the update for the directive as well just get the reference to the directive via ViewChild.

**Comment by armangevorgyan** [comment]
<mat-card-content [perfectScrollbar] #psScroll>
 in this case 
  @ViewChild('psScroll') private psScroll: PerfectScrollbarComponent(or  PerfectScrollbarDirective);
    this.psScroll.directiveRef.update();
 does not work;
in this case   <perfect-scrollbar class="ob-drag-drop__area" #psScroll> work

**Comment by sconix** [comment]
With directive you already have the directive reference so you need to just call this.psScroll.update().

**Comment by armangevorgyan** [comment]
OK  :)), but with directive @ViewChild('psScroll') -->this.psScroll  is undefined

**Comment by sconix** [comment]
That you need to figure out yourself :) Not specific to this library, you can check the example app which uses both (component and directive reference) for clues. I am not sure but perhaps directive reference is connected later than component so you might need to hold on calling update until ngAfterViewInit instead of ngOnInit for example.
