### ISSUE TITLE
Uncaught TypeError: core_1.OpaqueToken is not a constructor

### ISSUE THREAD

**Issue by yuliankarapetkov** [zefoy/ngx-perfect-scrollbar#113]
Upon importing the module in my core module, I get the following error in my browser's console:

_Uncaught TypeError: core_1.OpaqueToken is not a constructor_

![image](https://user-images.githubusercontent.com/6671521/32551748-6fdef412-c489-11e7-8cc7-805b04381600.png)

**Comment by sconix** [comment]
With Angular 5 you need to use 5.x version of this library. There is a pre-release out with @next tag, official 5.0.0 version of this library will be released during this week.

**Comment by danielgolub** [comment]
@next now makes this error:
ERROR in node_modules/ngx-perfect-scrollbar/dist/index.d.ts(3,30): error TS2305: Module '"/node_modules/ngx-perfect-scrollbar/dist/lib
/perfect-scrollbar.interfaces"' has no exported member 'PERFECT_SCROLLBAR_CONFIG'.
node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts(1,31): error TS2305: Module '"/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**Comment by sconix** [comment]
You still have 4.x version of this library, in 5.x version there is no OpaqueToken used. You should get 5.0.0-9 version with the next tag.

**Comment by sconix** [comment]
There is now official 5.0.0 release out of this library.
