### ISSUE TITLE
Could you please fix this issue. Angular 5  has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by vmarimuthu** [zefoy/ngx-perfect-scrollbar#114]
ERROR in node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts(1,31): error TS2305: Module '"C:/work/tttt/my-app/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

Could you please fix this issue. It's really blocking my migration.

**Comment by sconix** [comment]
See #113 for an answer.

**Comment by sconix** [comment]
There is now an official 5.0.0 release out of this library.

**Comment by sameena99** [comment]
Hey, i am getting the same issue while using perfectscrollbar.
Did you find its solution?

**Comment by vmarimuthu** [comment]
5.x fixed this issue.

**Comment by Inframatic** [comment]
I have angular 5.2.2 and this does not fix the issue. I am little worried when I see issues with this OpaqueToken issue being prematurely closed. It doesn't seem like this problem has been properly fixed although I dont think this is a ngx-perfect-scrollbar issue

**Comment by kim-btm** [comment]
I agree. I have the same issue as of today while installing with the latest version of Angular.

**Comment by sconix** [comment]
There is no OpaqueToken in any of the 5.x versions of this library. So if you get the error then you are using 4.x version which is meant for Angular 4.x.
