### ISSUE TITLE
Multiple perfect-scrollbars with scroll up on change content

### ISSUE THREAD

**Issue by SebastianRuecker** [zefoy/ngx-perfect-scrollbar#115]
Hi there,
i wanted to realize a dashboard with bs4 cards and the card-block should be scrollable.

example: `<div class="card"><div class="card-header>...</div><div class="card-block"><perfect-scrollbar>...</perfect-scrollbar></div>...<div class="card"><div class="card-header>...</div><div class="card-block"><perfect-scrollbar>...</perfect-scrollbar></div>`

on my first card the scroll up function works by adding `@ViewChild(PerfectScrollbarComponent) componentScroll: PerfectScrollbarComponent;` and in the change function `this.componentScroll.directiveRef.scrollToTop();` 

how can i realize this for the other cards?

**Comment by sconix** [comment]
This is more of a question for stackoverflow / angular forums and not an issue. You can name the components or use ViewChildren.
