### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ../../Observable

### ISSUE THREAD

**Issue by costea93** [zefoy/ngx-perfect-scrollbar#117]
Hey guys i did everything as on instructions but i got this error:

ERROR in ./~/ngx-perfect-scrollbar/bundles/ngx-perfect-scrollbar.umd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../Observable in D:\Development\project\node_modules\ngx-perfect-scrollbar\bundles
 @ ./~/ngx-perfect-scrollbar/bundles/ngx-perfect-scrollbar.umd.js 8:19-46 13:21-48

what's the problem here?

**Comment by sconix** [comment]
Do you have rxjs package installed? But I assume that you are using SystemJS and there is a bug in rxjs 5.5.2 (which is required by Angular 5) that gives an error. So you need to do some extra tweaks atm to get SystemJS going with rxjs 5.5.2.

**Comment by GrandSchtroumpf** [comment]
I have to "Module not found: Error: Cannot resolve 'file' or 'directory' ../../Observable" problem also.
I'm using Angular Universal starter (https://github.com/angular/universal-starter) which is based on angular CLI (so Webpack). Which version of rxjs should we use ?

**Comment by sconix** [comment]
I assume that you are using the 5.0.0 version of this library. So with Angular 5 you need 5.5.2 rxjs. The webpack example app is fully working if you need to check for clues. With angular-cli project you don't need to do anything special since rxjs dependencies etc. are correctly in place.

**Comment by GrandSchtroumpf** [comment]
I have the 5.0.0 version of this library, Angular 5 and rxjs 5.5.2. It works with "ng serve", but once build and opened with a node server it shows "Error: Cannot find module '../../Observable'"... I'll check the example.

**Comment by sconix** [comment]
OK, let us know if you find any solution. If you can't resolve it then maybe I could have look into universal-starter when I have the spare time. It just looks like a normal angular-cli setup so thats why I am bit baffled why it would not work since this is working perfectly in our angular-cli project and also in a newly created angular-cli project.

**Comment by saltyReef** [comment]
I too am having this same issue when using the latest version. Reverting back to version 5.0.0-9 works for me. Using the 5.0.0 release forced me to update the source to fix the paths for Observable etc.

**Comment by sconix** [comment]
So you mean that 5.0.0-9 works for you but 5.0.0 does not? I now looked at the umd bundle and it does have bit weird require paths for Observable. Not sure what did change between 5.0.0-9 and 5.0.0 that could have caused such a change. I'll have another look tomorrow if something changed in the umd bundle packaging.

**Comment by sconix** [comment]
I can verify now that something has changed between the last pre-release and final release in the umd packaging which is causing the error. I'll try to figure out the reason and make a new release. I was so sure that the cause was not in the library since I did not do any big changes after the last pre-release which I tested to work.

**Comment by sconix** [comment]
Ok so I have forgot to update the rxjs imports after updating the rollup bundle config. Sorry about the hassle and not testing properly the latest version, but I was sure I did not do any changes that could break something. I will release 5.0.1 in few minutes which fixes this issue.

**Comment by saltyReef** [comment]
Thanks for the quick fix.

**Comment by sconix** [comment]
Thank you for letting me know the working version, would not believed the error to be due to packaging otherwise. Rollup is new to me so don't know yet all the errors there can be due to miss configuration etc.
