### ISSUE TITLE
Scroll animation stops prematurely in Chrome on a zoomed out page

### ISSUE THREAD

**Issue by arusak** [zefoy/ngx-perfect-scrollbar#118]
We're using your component in our medical app, and it's doing great. Recently I faced a problem. Sometimes when I used scrollToBottom(0, 100) method, it worked fine and sometimes it stopped prematurely. So the debugging was started and I found out that when our app runs in Chrome and is zoomed out (to 80% for instance), the bug appears. 

It is caused by Chrome setting scrollTop attribute of the scrolled element to fractional values when an integer is specified. E. g., you say el.scrollTop = 120, then you inspect el.scrollTop and it says like 119.5 or so. 

Your component is treating such a situation as if user has scrolled, so it stops working. I offer a small fix which solves the problem.

**Comment by sconix** [comment]
Thanks for bringing this to my attention and providing PR.
