### ISSUE TITLE
perfect_scrollbar_1.default is not a constructor

### ISSUE THREAD

**Issue by uazure** [zefoy/ngx-perfect-scrollbar#120]
Getting above error after installing `npm install ngx-perfect-scrollbar@4.9.5` (same for 4.9.4, 4.9.3) and trying to use perfect scrollbar directive.

Debugging the perfect-scrollbar.directive.js I see:

```
var perfect_scrollbar_1 = require("perfect-scrollbar");
...
var perfect_scrollbar_interfaces_2 = require("./perfect-scrollbar.interfaces");
...
PerfectScrollbarDirective.prototype.ngAfterViewInit = function () {
    ...
    var config_1 = new perfect_scrollbar_interfaces_2.PerfectScrollbarConfig(this.defaults);
    config_1.assign(this.config);
    _this.ps = new perfect_scrollbar_1.default(_this.elementRef.nativeElement, config_1);
```
JS compiler fails to execute default method of perfect_scrollbar_1 because its undefined.
The relevant ts code from source for this is:

```
import PerfectScrollbar from 'perfect-scrollbar';
import { PerfectScrollbarConfig, PerfectScrollbarConfigInterface } from './perfect-scrollbar.interfaces';
...
ngAfterViewInit() {
...
    const config = new PerfectScrollbarConfig(this.defaults);
    config.assign(this.config);
    this.ps = new PerfectScrollbar(this.elementRef.nativeElement, config);
```

As I understand, the issue is caused by different module formats and different `require` implementations in build systems.
I use webpack as bundler and at-loader. Config for tsconfig is the following:
```
        "compilerOptions": {
            "target": "es5",
            "module": "commonjs",
            "moduleResolution": "node",
...

    "awesomeTypescriptLoaderOptions": {
        "useBabel": true,
        "useCache": true,
        "usePrecompiledFiles": true,
        "useTranspileModule": true
    },
```

It looks very similar to tsconfig in ngx-perfect-scrollbar.

So the question is: what exactly is causing the problem and how to work it around?

**Comment by sconix** [comment]
First of all do you have correct version of the perfect-scrollbar? 4.9.x version of this library requires 1.x version of the perfect-scrollbar and if you have the old 0.8.x for some reason then it would also produce similar error since the old version is not instantiated through creating new instance.

**Comment by uazure** [comment]
@sconix you're right! The problem I faced was caused by the perfect-scrollbar v0.6 that was previously installed. So cleaning node_modules and npm install resolved the issue. Thanks for quick reply!
