### ISSUE TITLE
The scrollbar can not work in right way  when update to version 5.0.2

### ISSUE THREAD

**Issue by hpyou** [zefoy/ngx-perfect-scrollbar#121]
![gif](https://user-images.githubusercontent.com/15992591/33157994-378412d2-d041-11e7-91e7-611036a9513a.gif)

**Comment by hpyou** [comment]
I find I must add style ` position: relative; ` to the scrollbar host, and then it works

**Comment by sconix** [comment]
Yes this was changed in 5.0.0. The directive wont anymore set the position relative automatically, this was due to having less inputs for the directive and making the directive work more like the pure perfect-scrollbar which also needs the position: relative to be set.
