### ISSUE TITLE
Error with ng@5.0.x upgrade

### ISSUE THREAD

**Issue by jspizziri** [zefoy/ngx-perfect-scrollbar#122]
I'm using webpack, not SystemJS. Upgraded to `ngx-perfect-scrollbar@5.0.x` and am getting the following error at compile time:

```
ERROR in ./~/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'perfect-scrollbar' in '/srv/app/node_modules/ngx-perfect-scrollbar/dist'
 @ ./~/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js 4:0-49
 @ ./src/app/calendar/calendar.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts
```

Packages installed:
```
"@angular/animations": "^5.0.3",
"@angular/common": "^5.0.3",
"@angular/compiler": "^5.0.3",
"@angular/core": "^5.0.3",
"@angular/forms": "^5.0.3",
"@angular/http": "^5.0.3",
"@angular/platform-browser": "^5.0.3",
"@angular/platform-browser-dynamic": "^5.0.3",
"@angular/router": "^5.0.3",
"ngx-perfect-scrollbar": "^5.0.5",
"rxjs": "^5.5.2",
```

**Comment by sconix** [comment]
You don't have perfect-scrollbar installed. Npm should install it as dependency, but seems like it has not done it.

**Comment by jspizziri** [comment]
Very strange, I removed all my `node_modules/` and did a reinstall. It installed the `perfect-scrollbar` dependency but it didn't install the `resize-observer-polyfill` dependency.

Now I'm getting a:

```
ERROR in ./~/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'resize-observer-polyfill' in '/srv/app/node_modules/ngx-perfect-scrollbar/dist'
 @ ./~/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js 5:0-54
 @ ./src/app/calendar/calendar.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts
```

I'm not sure why npm is having issues during the install, I haven't had it with any other modules. Not sure if you might have any insight into this, but it seems like it's more likely with my local env than this package.

**Comment by sconix** [comment]
At least older npm versions have had often trouble with cache etc., but at least for me latest 5.x npm has done a much better job than the old 4.x etc.

**Comment by jspizziri** [comment]
Yeah, I've just found an open issue for npm@5.x for a similar problem here https://github.com/npm/npm/issues/16839, just FYI. Thanks for the help!

**Comment by jspizziri** [comment]
To fix I did the following as (referenced in the ticket above):

```
rm -rf node_modules/
rm package-lock.json
npm install
```

which correctly built the package-lock and installed the dependency.
