### ISSUE TITLE
Directive not working in Example App if started with Directive showing

### ISSUE THREAD

**Issue by NejcCarl** [zefoy/ngx-perfect-scrollbar#125]
I have an issue when using [perfectScrollbar] directive and I can reproduce this issue in example app for Angular 4. The container with this directive is scrollable and I have checked PerfectScrollbar in debugger and it has right dimensions for containerHeight, containerWidth and contentHeight, contentWidth. But the scrollbar is not visible and is under the content and its height is added to content height.

You can reproduce the issue in Example App by setting:
public type: string = 'directive';

The scrollbar will not show. If you now click on "Switch to component" button and then back on "Switch to directive" button it will work as expected.

**Comment by sconix** [comment]
Sounds odd, but I will test tomorrow.

**Comment by NejcCarl** [comment]
Okay, thank you!

**Comment by sconix** [comment]
Ah this is because the index.html still has the 0.8.x perfect-scrollbar styles. I updated the index.html to load the correct style sheet.
