### ISSUE TITLE
Angular 5 AOT Issues  -resolving symbol PERFECT_SCROLLBAR_CONFIG

### ISSUE THREAD

**Issue by zrilo** [zefoy/ngx-perfect-scrollbar#128]
I have upgraded to angular 5, ngx-perfect-scrollbar 5.0.5 and when running ng server -aot get the following.

ERROR in Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 2:22 in the original .ts file), resolving symbol PERFECT_SCROLLBAR_CONFIG in .... /node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.interfaces.d.ts, resolving symbol AppModule in ....

My app.module.ts file  implementation is as per instructions, this was working fine with aot builds before upgrading

Please help thanks

**Comment by sconix** [comment]
What build system are you using? Never seen such an error, the example app uses custom webpack setup and our application angular-cli. Both are working just fine for AOT building so the problem is most likely in your build system setup.

**Comment by zrilo** [comment]
```
Angular CLI: 1.5.4
Node: 6.2.0
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.4
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc.2
@angular/platform-server: 5.0.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by sconix** [comment]
I would try re-installing node_modules and maybe try cleaning npm cache. We are also using angular-cli 1.5.x and have no problems.
