### ISSUE TITLE
Manual update refresh issue

### ISSUE THREAD

**Issue by hgoraya** [zefoy/ngx-perfect-scrollbar#13]
if  i m trying to update scroller manually  i.e. calling update method , it doesn't refresh handle bar width automatically. 
I need to click on scrollbar handle to update its correct length.

can you give example how to use MutationObserver to call update method?

i am using Ng2 with typescript.

thanks
hardev

**Comment by sconix** [comment]
I can't see why it would not, would it be possible to get Plunker example? Since I would like to see why you need to call update manually.

**Comment by hgoraya** [comment]
Unfortunately I can not reproduce this bug. I am using the scrollbar in a webapp and I can not share this code. Can you provide basic example for manual update of scroller.

**Comment by sconix** [comment]
I suspect that its something in you app that breaks the change detection. There is no simple example of manual update, the library provides update function call which you can call to refresh the scrollbar, but where you want / need to call it is totally up to your application and how have you build / optimized the change detection. 

If I understand correctly that you are calling the update, but you still don't get correctly sized scrollbar handle and if that is the case then most likely you have some styles issue which causes the scrollbar getting rendered wrongly when you call the update function or just timing issue when calling the update.

One thing that I noticed with Swiper library is that if I destroyed and created the Swiper in same function call the styles wont get refreshed properly by the browser. To fix that I placed the Swiper re-initialization inside a timeout. So you could try for example calling the update via setTimeout(() => {scrollbarView.update();}, 0) to see if that helps.
