### ISSUE TITLE
OpaqueToken is deprecated

### ISSUE THREAD

**Issue by GrandSchtroumpf** [zefoy/ngx-perfect-scrollbar#130]
Hello,
OpaqueToken is deprecated since Angular 4. I'm not sure but I think you can change it for InjectionToken in lib/perfect-scrollbar.module.d.ts =)

**Comment by sconix** [comment]
You need to upgrade to 5.x version of this library if you are using Angular 5.

**Comment by GrandSchtroumpf** [comment]
Hmmm, I have the version 5.0.5 and I've got this error on my console : "s.OpaqueToken is not a constructor" for a prerender Angular Universal app...

**Comment by sconix** [comment]
You can't have 5.x version and get that error. There is no OpaqueToken used in the 5.x version. So try wiping node_modules etc. the usual trills to sort out your packages.

**Comment by GrandSchtroumpf** [comment]
Ok it works ! I had to uninstall and reinstall the package several times, but it finally works ! Thank you =)
