### ISSUE TITLE
Angular 5: Problem with directiveRef, no Scrolling

### ISSUE THREAD

**Issue by AlerpCoder** [zefoy/ngx-perfect-scrollbar#131]
Hello,

since the newest update form `ngx-perfect-scrollbar` with the version 5.0.5, I cannot use the functions `scrollToBottom` and `scrollToTop` anymore. 

I get everytime the Error below:

```core.js:1350 ERROR TypeError: Cannot read property 'update' of undefined
    at step_1 (ngx-perfect-scrollbar.es5.js:493)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
    at timer (zone.js:1896)```

**Comment by sconix** [comment]
Hard to say whats wrong with that error. We don't have any issues and also in the example app both functions seem to work well. Are you calling those functions with some offset/speed parameters or without?

**Comment by AlerpCoder** [comment]
Yes i am calling both functions with offset and speed parameters

**Comment by sconix** [comment]
Have you tried without them? I wonder if it the value for one of them that is causing the issue. For example there is no check for the given offset if its a valid value. If that can cause an error I could add some checks.

**Comment by AlerpCoder** [comment]
Hello @sconix the offset of my functions is 0. 
Here the line

`@ViewChild('scrollBar').directiveRef.scrollToBottom(0, scrollTime);`

**Comment by sconix** [comment]
Not sure if that is proper usage of ViewChild decorator. At least I tried that and it did not work, there was no error though. So I think you should try the recommended way to use the view child i.e. use it define the reference before constructor.

At least I verified that there is no offset or scroll time value that would cause errors. So I strongly believe that the way (or when) you are calling the directiveRef is not supported by Angular.

**Comment by AlerpCoder** [comment]
sry I tried to simplify the code. 
```
@ViewChild('scrollBar') bar: any;.
...
this.bar.directiveRef.scrollToBottom(0, scrollTime);

```
It worked with the Version 4.6.3

**Comment by sconix** [comment]
At least I can not replicate this problem in any way I try. And since the error you pasted in your first post does not say where the fault could be its really hard to guess what could cause the issue.

Can you paste the very first line of the error as well? Since I think its missing since there is no line saying what the error is just where it is happening.

**Comment by sconix** [comment]
I guess you got the issue resolved, if not then please try to reproduce the problem in Plunker (you can find a link to a template in the README):
