### ISSUE TITLE
 Cannot read property 'destroy' of undefined, when trying to destroy disabled element.

### ISSUE THREAD

**Issue by korobkov-k** [zefoy/ngx-perfect-scrollbar#133]
Hi, I was using v 4.9.5 when I faced this issue. I had some elements with `[perfectScrollbar] `and `[disabled]="true"` inside of a ngFor list. When I tried to update the list I got this error:

 Cannot read property 'destroy' of undefined at eval (perfect-scrollbar.directive.js:66)

After some time of investigation I found out, that it is caused by `[disabled]` property. The thing is that directive tries to destroy instance of PerfectScrollbar, that was never initialized/created.

**Comment by sconix** [comment]
This is fixed in 5.x releases.

**Comment by sconix** [comment]
I also released 4.9.6 that has a fix for this.
