### ISSUE TITLE
Native scrollbar flickering on/off during window resize..

### ISSUE THREAD

**Issue by designcourse** [zefoy/ngx-perfect-scrollbar#135]
On Chrome Version 63.0.3239.84:

![image](https://user-images.githubusercontent.com/15989197/33967892-699c4922-e033-11e7-8f6c-1e727adf4a9a.png)

I wasn't sure if this is something that has already been addressed from:
https://github.com/zefoy/ngx-perfect-scrollbar/pull/53/commits/d22f4766fe8165d80d64c0daf83ca89e5e01eb54

...or if I need to integrate that somehow..

**Comment by sconix** [comment]
It has nothing to do with that change and that resize handling has been removed long time a go. I believe that the issue is that I am missing overflow: hidden from the main element which causes this problem. I will make a fix soon.

**Comment by sconix** [comment]
You can have a look from the commit how to fix this with styles. The fix will be included in next release which should be out next week.

**Comment by designcourse** [comment]
That fixed it, thanks a lot!  Great project here.
