### ISSUE TITLE
NPM Module

### ISSUE THREAD

**Issue by valera-rozuvan** [zefoy/ngx-perfect-scrollbar#137]
Why are there 2 NPM modules:

- https://www.npmjs.com/package/angular2-perfect-scrollbar
- https://www.npmjs.com/package/ngx-perfect-scrollbar

that lead to this repository?

**Comment by sconix** [comment]
Because the angular2 package is from the time of Angular 2 and ngx is the new package for angular 4/5 and future versions.

**Comment by valera-rozuvan** [comment]
Thank you for making it clear :smile:
