### ISSUE TITLE
Unable to set scrollXMarginOffset

### ISSUE THREAD

**Issue by konasunny** [zefoy/ngx-perfect-scrollbar#138]
I Have a requirement to set the scroling top postion to be start 50px. 
so i tried to use the scrollXmarginOffset: 50 but it doesnt work. Can any one help to resolve this issue.

public config: PerfectScrollbarConfigInterface = { scrollYMarginOffset: 50 };

**Comment by sconix** [comment]
Can you be bit more specific what you are trying to do. If you just want to set the initial scroll position then you need to use the api functions to set the position after rendering.
