### ISSUE TITLE
ERROR in : Unexpected value 'PerfectScrollbarModule

### ISSUE THREAD

**Issue by ericel** [zefoy/ngx-perfect-scrollbar#139]
ERROR in : Unexpected value 'PerfectScrollbarModule in D:/websites/eeee/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts' imported by the module 'UsersModule in D:/websites/eeee/src/app/public/content/users/users.module.ts'. Please add a @NgModule annotation.

Am not sure if this is an issue with just lazy-loaded routes.
But my ```ng build --prod``` keeps failing

**Comment by sconix** [comment]
Can't say what could cause the error, but its something with your setup. Maybe you are not exporting the module properly or are importing it in wrong module etc. We use this library with angular-cli and lazy modules without any build issues. I have seen that error with some other libraries in our project, but can't remember what was the cause so sorry that I can't be more help to you.

**Comment by vugar005** [comment]
the temporary solution is to use ng build --prod --aot=false

**Comment by vugar005** [comment]
Had exact issue before. Issue solved thanks to @sconix. The problem probably because you import module from ngx-perfect-scrollbar/dist
instead of ngx-perfect-scrollbar.
