### ISSUE TITLE
Angular 2.4.0, function calls are not supported in app.module.

### ISSUE THREAD

**Issue by vapits** [zefoy/ngx-perfect-scrollbar#14]
Hi there,

My current setup is as in the docs meaning:
```bash
const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};
```
Which I call in the imports:
```bash
PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)
```

Though after the update to Angular 2.4.0 I'm getting the following error when I'm compiling the project:
>ERROR in Error encountered resolving symbol values statically. Calling function 'PerfectScrollbarModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Projects/WebApp/src/app/app.module.ts, resolving symbol AppModule in /Projects/WebApp/src/app/app.module.ts

The project still runs though.

I tried to wrap it in an exported functions as it requests but it seems that it is no working. Any idaes on this?

**Comment by sconix** [comment]
I am looking into this just now, new release will come later today to fix this when I figure out the problem.

**Comment by vapits** [comment]
Thx @sconix that was fast!
If you figure this out before releasing the new version please share it also here as a workaround.

**Comment by sconix** [comment]
This seems to need rather big build system updates, but at least it should bring AOT support as well. So no update today, but hopefully tomorrow everything is ready and I can release 2.0.0.

**Comment by sconix** [comment]
I have the new build system ready now and the upcoming 2.0.0 version will include both umd bundles and aot compatible library. I will make the release right after Christmas.
