### ISSUE TITLE
update doesnt work in content change

### ISSUE THREAD

**Issue by amirbashiri** [zefoy/ngx-perfect-scrollbar#140]
hi
i change content of my component by click on button
but scrollbar doesnt update automatically,and event with update( ) method
please check it
thanks

**Comment by sconix** [comment]
You most likely have some sort of timing problem. You must always remember that if you change some value dynamically the change is not updated to DOM right away. So you are most likely calling update before Angular change detection has picked up the change and updated the DOM.

The problem with pure JS libraries like perfect-scrollbar is that they work in DOM space and Angular does not so sometimes its hard to get the timing right when the template changes dynamically.
 
This library uses resize observer to notice the DOM changes and it should pick most of the changes out of the box and update perfect-scrollbar at correct moment. If you can reproduce the problem with the provided Plunker template then I could have a look and try to figure out why the "automatic" content change detection system is not working.

**Comment by hmuller** [comment]
sconix is https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver working with the same timing as resize?

I think the scrollbar could contain nested components from various authors working in various ways. Isn't worth to implement option to auto refresh scrollbar with given time interval?

**Comment by sconix** [comment]
In 90% of cases the resize observer should work, for the rare and complex situations manual update call is the best. Timed intervals are never a good solution performance vice. If somebody eants such thing they can very easily implement such thing with couple lines of code, but it doed not make sense to include such "bad" options within the library.

**Comment by amirbashiri** [comment]
thanks for answer
i cant example my component in Plunker because of some reasons.
my component do some thing like tab component. when user clicked on category item , i change tab value according to category id. but scrollbar doesnt update automatically, event i use manual update like below code:
this.componentScroll.update();
but its not work anyway!

**Comment by sconix** [comment]
The only possibility is that when you call the update the DOM is not ready / updated yet. I don't know how else to describe the problem, if you understand how Angular works vs traditional Javascript libraries such as perfect-scrollbar fixing this sort of problems is easy. Without means to replicate the problem its very hard to give exact pointers how you could fix your code.
