### ISSUE TITLE
AOT problem when using lazy-loading. Unexpected value 'PerfectScrollbarModule' imported by the module

### ISSUE THREAD

**Issue by vugar005** [zefoy/ngx-perfect-scrollbar#143]
Hi
When running ng build --prod error occurs stating that
`ERROR in : Unexpected value 'PerfectScrollbarModule in D:/vugar/TMIS-app/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts' imported by the module 'AppModule in D:/vugar/TMIS-app/src/app/app.module.ts'. Please add a @NgModule annotation.`
Happened right after implementing lazy loading.
Problem is not emitted with ng build --prod --aot=false or  just ng build .
Reinstalling perfect scrollbat not fixing issue.

My shared Module:
```
const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};
 declarations: [
     ...
  ],
  exports: [
    CommonModule,
    .....
    PerfectScrollbarModule
  ],
  providers: [{
      provide: PERFECT_SCROLLBAR_CONFIG,
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
    }
]
```
App Module:
same configuration as in Shared Module.

Lazy modules just import Shared Module,
I looked at previous same issue without useful info. 
Please do not close this issue by claiming I have configuration issue. Thank you for project, I am using the plugin  more than a year and have not such issue so far. It happens when implementing lazy-loading and  aot simultaneosly. Hope this time you solve issue.

Angular: 5.1.2
ngx-perfect-scrollbar:  5.3.1

**Comment by sconix** [comment]
There is no such thing as lazy loading not support when AOT compiling. I.e. libraries do not need to do anything to support AOT with lazy loading. You need to check your modules configuration, we are using this library in lazy loaded modules in angular-cli project and have no issues (with same versions).

I have sometimes seen people reporting these weird NgModule annotation errors but nobody ever posted a solution so not sure what they did to fix the error. I have actually got this error once with another library, but can't remember what fixed it. Maybe one thing to try is to wipe npm cache and try installing the package again if the module configuration is correct.

**Comment by vugar005** [comment]
@sconix  I somewhat identified the problem . Found that  issue occurs when PerfectScrollbarModule and its providers: 
```
 {
    provide: PERFECT_SCROLLBAR_CONFIG,
    useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
  }
```
are declared in App Module. But when I declare them ONLY in Core Module and import Core module to App Module  the error does not happen.
Here is how core module and app module looked when error existed:
Core Module before:
```
@NgModule({
  providers: [
    AuthService,
    UniversityAsideService,
    StructureService,
    EmployeeService,
    StudentService,
    OrderService,
    DiplomaService,
    AuthGuard,
    SharedService,
    NestedResolver,
    /*  { provide: RouteReuseStrategy, useClass: CustomReuseStrategy },*/
  ]
})
export class CoreModule {
}
```
App Module before:
```
const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};
NgModule({
  declarations: [
    AppComponent,
    AuthComponent,
    HeaderComponent,
    UniversityAsideComponent,
    UnibookComponent,
    NotFoundComponent,
    AddressDialogComponent
  ],
  entryComponents: [
   AddressDialogComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    CoreModule,
    AppRoutingModule,
    MatSidenavModule,
    MatButtonModule,
    MatSelectModule,
    HttpClientModule,
    NgbModule.forRoot(),
    ModalModule.forRoot(),
    ReactiveFormsModule,
    SelectModule,
    ResponsiveModule,
   PerfectScrollbarModule
  ],
 providers: [
 {
      provide: PERFECT_SCROLLBAR_CONFIG,
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
    }],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Core Module after:

```
const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};
@NgModule({
  imports: [
   PerfectScrollbarModule
  ],
  providers: [
    AuthService,
    UniversityAsideService,
    StructureService,
    EmployeeService,
    StudentService,
    OrderService,
    DiplomaService,
    AuthGuard,
    SharedService,
    NestedResolver,
    {
      provide: PERFECT_SCROLLBAR_CONFIG,
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
    }
    /*  { provide: RouteReuseStrategy, useClass: CustomReuseStrategy },*/
  ]
})
export class CoreModule {
}
```
App module after:
```
@NgModule({
  declarations: [
    AppComponent,
    AuthComponent,
    HeaderComponent,
    UniversityAsideComponent,
    UnibookComponent,
    NotFoundComponent,
    AddressDialogComponent
  ],
  entryComponents: [
   AddressDialogComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    CoreModule,
    AppRoutingModule,
    MatSidenavModule,
    MatButtonModule,
    MatSelectModule,
    HttpClientModule,
    NgbModule.forRoot(),
    ModalModule.forRoot(),
    ReactiveFormsModule,
    SelectModule,
    ResponsiveModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
What might be the cause of this error? It is not good idea to import PerfectScrollbar in core module .
Thanks

**Comment by sconix** [comment]
If I understand correctly you are trying to provide the configuration in two modules. If so then thats the problem, the configuration you should only provide in one module (in root module). The configuration is also available to the lazy loaded module so you can just import the PerfectScrollbarModule without providing the configuration. Also notice that providing the global configuration is fully optional.

I will update the documentation to say that the configuration should be provided only once.

**Comment by vugar005** [comment]
@sconix  . I removed the config from shared module. 
Shared module  now import perfectscrollbar module without config. 
App module imports perfectscrollbar with config. 
Core module imports neither module nor config. 
Problem still exists in ng build --prod.
Have no idea how to solve that.

**Comment by vugar005** [comment]
When I import PerfectScrollbarModule and its config to core.module the problem does not happen. But when importing  module and config to App module only ( where it should be located) the issue raises here.
So Error raises when importing config to App module.(even though I import config once in whole app).
I am sure there is something wrong with the plugin.

**Comment by sconix** [comment]
The reason why i don't believe the issue be in this library is as I said that libraries don't need to do anything to support AOT / lazy loading etc. Libraries just provide a module and in this library the module is the simplest possible.

I still have hard time understanding your application structure since I don't see route configuration in any of those modules so could you share your routing configuration so I have a bit better understanding how your app is build.

**Comment by sconix** [comment]
So if I understand correctly your app structure the way you should have it setup is:

- Provide the default config in your AppModule (at least I think this is your root module)
- Then import the PerfectScrollbarModule in the modules where you use it (or in the shared module if thats the purpose)

Nothing else should be needed.

**Comment by vugar005** [comment]
please see my project in https://github.com/vugar005/TMIS-app
Please browse commits.
Application worked till  'added core module'  included.
Stopped working in 'backup' commit .

**Comment by sconix** [comment]
I see at least on problem right away, in you app module you have import PerfectScrollbarModule from ngx-perfect-scrollbar/dist and not ngx-perfect-scrollbar. If that wont help then just setup it like I said in my previous comment and it will work.

**Comment by vugar005** [comment]
Thank you so much! That'ts what the problem is. It is strange the module is auto imported by WebStorm. So I did not even think about wrong import . Webstorm imports incorrectly in App Module but in all other modules correctly.  Sorry for inconvenience. Closing the issue.
