### ISSUE TITLE
Scrollbars don't appear if content is added after initialization

### ISSUE THREAD

**Issue by mischkl** [zefoy/ngx-perfect-scrollbar#146]
We have a list of items (as *ngFor) that is loaded from a service after the component is initialized - this is the content of the perfect-scrollbar. Unfortunately the scrollbar is not shown until after the user starts scrolling.

**Comment by sconix** [comment]
This library uses mutation observer which should pick up changes caused by ngFor and call update automatically. For some reason its not doing it for you and then your only option is to call update method manually after the content has changed.

**Comment by mischkl** [comment]
Hmmm. What should I call the update method on? The directive?

**Comment by sconix** [comment]
Yes. Directive provides update method which calls the update of perfect-scrollbar.

**Comment by hneuer** [comment]
We have the same problem using the perfect-scrollbar component. Here is a Plunker to reproduce: http://plnkr.co/edit/zzusIY0X4maMG9cOGqOI?p=preview
After clicking 'Add' the scrollbar won't appear until the user starts scrolling.

Note: This seems to happen with ngFor inside as well as with a simple binding to text (as in the Plunker).

**Comment by sconix** [comment]
Thanks for the example I will have a look if there is something I can do in the wrapper or if it could be even perfect-scrollbar bug.

**Comment by sconix** [comment]
I added resize observer for the first child as well, this seems to fix this issue. I will soon release 5.3.3 which should fix this issue, if not please let me know.

**Comment by hneuer** [comment]
Thanks a lot, works like a charm now!
