### ISSUE TITLE
how to build the dist and publish to npm.js

### ISSUE THREAD

**Issue by dyh333** [zefoy/ngx-perfect-scrollbar#148]
as the title, I had a similar project, but I don't know how to build a published dist , could you kindly show your method? thanks.

**Comment by dyh333** [comment]
I run the npm start, but show bug like below:
![image](https://user-images.githubusercontent.com/1221313/35372496-44ff8656-01d5-11e8-9580-4eb5d77b829f.png)

**Comment by sconix** [comment]
Don't understand what there is to show. All the configs are in the repository.
