### ISSUE TITLE
Rail y is on the left

### ISSUE THREAD

**Issue by sambaptista** [zefoy/ngx-perfect-scrollbar#149]
Hi !

I observed a bug where the `<div class="ps__rail-y" style="top: 2014px; left: 0px; height: 400px;">` is aligned on the left instead of the right (the scrolling works and the container is full-width). 

It requires multiples elements combined to be observable : 

- First page load : refresh or `enter` key on url bar. When navigating routes in the app context without refresh, the scroll is correctly right aligned.
- Used in a component displayed in y a `child route`
- Used if a `router-outlet` is used in a `mat-sidenav-container` ( angular material 2)
- Seems to require to be a sub-child route (direct child seems not to be bugged).

Here is the most minimalistic reproduction of the bug I could create : https://github.com/sambaptista/ngx-perfect-scrollbar-bug .

To launch, execute `npm/yarn install` and `ng serve`

**Preview :** 

<img width="400" alt="capture d ecran 2018-01-28 19 24 53" src="https://user-images.githubusercontent.com/5111137/35485511-f522009e-0460-11e8-8be8-90594aed48a4.png">

Thx for your job, and I hope I give enough detail for you to investigate. Keep me informed if you need some improvements/tests on my repo.

**Comment by sconix** [comment]
Thanks for the reproduction, it seems that for some reason PS is adding left style to the scrollbar. Might be a bug or something causing it, but I can fix this easily with one style addition. I will release a new version with the fix.

**Comment by sambaptista** [comment]
I think there is something similar to that on the top attribute on the horizontal scroll` <div class="ps__rail-x" style="left: 0px; top: 86.3636px; width: 979px;">`

On page load the scroll is almost on top of the page, instead of bottom. 

Do you want I try to reproduce it or you're ok with my first repo ?

**Comment by sconix** [comment]
I though I fixed it at the same commit but it seems that I forgot to add one line :) Will make new release soon.

**Comment by dana-c0914** [comment]
The change only applies to the component, if you use the directive, the style of `left: auto !important` is not applied.

**Comment by DzmVasileusky** [comment]
+1 
version 5.3.5

I have created stackblitz
https://angular-wapzv9.stackblitz.io

If the container is originally empty scrollbar will be on the left even after loading data into it and updating.

On top of it there is a bug that scrollable area become expanded and you can scroll much more than really occupied space.

**Comment by sconix** [comment]
The bug is in PS itself so there is not much I can do for that in this library except the style "fix".

**Comment by DzmVasileusky** [comment]
Ok, I'll move it to PS issues
