### ISSUE TITLE
what global in rollup-umd.config.js means?

### ISSUE THREAD

**Issue by dyh333** [zefoy/ngx-perfect-scrollbar#150]
hi, @sconix . I wanna know why you put rxjs in global config in rollup-umd.config.js? I am trying build ng module with rollup, but I am a starter. thanks

**Comment by sconix** [comment]
Well this is not a rollup forum and I am definitely not an expert on rollup I just use it :) Anyway you usually only want to pack up the library and leave out the other libraries from the bundle.
