### ISSUE TITLE
Relax ctrl+scroll event to allow zoom

### ISSUE THREAD

**Issue by sambaptista** [zefoy/ngx-perfect-scrollbar#151]
On some OS (windows + linux at least) using mousewheel while holding ctrl modifier cause the page to zoom.

It seems not allowed by this library and that breaks native behavior. Is there any config I can do to allow this again ? or is this a valid feature to ask ?

Imho the native features are important and should not be removed.

Maybe I'm in the wrong repository ? should I adress that request to the original lib ?

**Comment by sconix** [comment]
Yes you should address this issue for the original library.
