### ISSUE TITLE
Vertical scroll not working in IE (in demo)

### ISSUE THREAD

**Issue by Robyn13** [zefoy/ngx-perfect-scrollbar#152]
![image](https://user-images.githubusercontent.com/22321100/35744077-00c716bc-0805-11e8-911c-0b2bf8ea6559.png)

**Comment by sconix** [comment]
I don't think Angular flex-layout supports IE10 nor should anything else for that matter :)

**Comment by Robyn13** [comment]
Screenshot is from IE11 which is supported according to the documentation.

**Comment by sconix** [comment]
Sorry my bad, I thought it looked like an IE10. I will make fix for IE11, thanks for reporting this.
