### ISSUE TITLE
Issue with scrollToElement for items with nested position:relative;

### ISSUE THREAD

**Issue by AndrewMAGIK** [zefoy/ngx-perfect-scrollbar#153]
Hi, 
Here is an issue with scrollToElement() functionality when I try to scroll top element that has position: relative inside another element with position: relative. Here is live demo:

http://plnkr.co/edit/O59w70tnPLhI7GG7RUFr?p=preview

Try to click on blue items - they works as expected (clicked element scrolls to top).
Then try to click on red items (for example on "id-70-3") and see that it scrolls somewhere down, but not to top.

This problems appear when LI element have "position: relative;" but sometimes it can't be removed from styles because this rule is needed for other inside items with position absolute.

**Comment by sconix** [comment]
Thanks for the reproduction, I will have a look tomorrow.

**Comment by AndrewMAGIK** [comment]
Thx for a fast bugfixing! 
Now it works a little bit better, but still not perfect as expected. 

Try to click twice on red "id-60-1" and see that every time scroll bar change its position.
But clicking many times on blue items - keep them on the same place as expected.

**Comment by sconix** [comment]
You should add stop event propagation call for the child clicks. At least to me it worked perfectly when adding that.

**Comment by AndrewMAGIK** [comment]
Yep, sorry.
Just tested on my project where exist event.stopPropagation() and everything works file without any additional changes from my side.
Thanks!
