### ISSUE TITLE
On reaching bottom, fires the event multiple times

### ISSUE THREAD

**Issue by sosharma1403** [zefoy/ngx-perfect-scrollbar#158]

**Comment by sconix** [comment]
I dont see this as a problem it might be wanted or not depends on what one uses the event for. If you think its a bug you should report it in perfect-scrollbar repository since this is just a wrapper.

**Comment by sconix** [comment]
Next major release has a new events handling that don't cause change detection and also does not send same event multiple times.

**Comment by sosharma1403** [comment]
Thanks :+1:
