### ISSUE TITLE
child div can't scroll 

### ISSUE THREAD

**Issue by paullauyc** [zefoy/ngx-perfect-scrollbar#159]
i am using perfect-scrollbar directive in my main DIV container. some how the child div elements can't scroll.  But they can scroll in my angular 4 version.

**Comment by sconix** [comment]
I don't quite get your problem description.

**Comment by paullauyc** [comment]
Actually, I  set the suppressScrollX is true for my global configuration. The child element can’t horizontally scroll

**Comment by sconix** [comment]
If this is still a problem then please provide a bit more complete description of the problem and I re-open the issue.
