### ISSUE TITLE
perfect-scrollbar/index.js not found

### ISSUE THREAD

**Issue by moniuch** [zefoy/ngx-perfect-scrollbar#160]
After installing ngx-perfect-scrollbar in Angular 5.2.5 (angular/cli, webpack) app I am getting this. Is it a bug or did I miss a step in installation? How can I point to the right file? Thanks

```
ERROR in ./node_modules/perfect-scrollbar/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/.../node_modules/perfect-scrollbar/index.js'
 @ ./node_modules/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js 4:0-49
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

("ngx-perfect-scrollbar": "^5.3.5",)

**Comment by sconix** [comment]
My guess is that you have wrong import part where you try to import from the library.

**Comment by moniuch** [comment]
I compared to the StackBlitz app and both have identical imports. But the ngx-perfect-scrollbar.es5.js has in line 4:
 `import PerfectScrollbar from 'perfect-scrollbar'`

How can is that expected to work if there is no index.js at the `perfect-scrollbar` root level?

**Comment by sconix** [comment]
The package.json always tells what index file to load and in what environments. So I am not sure what is wrong with your setup then. Maybe try re-installing this library if the package.json of the library is somehow corrupted.

**Comment by sconix** [comment]
What cli version do you have? Many of the cli versions have weird bugs so if you are running some beta version for example then thats most likely to be the culprit.

**Comment by moniuch** [comment]
(Thanks for responding so quickly)
The version is 1.6.8 - quite up to date. The problem might be that I first tried to install angular2-perfect-scrollbar and then after the OpaqueToken problem hit me, I uninstalled it. Will probably have to do a clean install.

**Comment by sconix** [comment]
Ok that might be it so maybe do a clean install and wipe npm cache as well just to be sure.

**Comment by moniuch** [comment]
Yes, that was it! Now works like a charm. Thanks - your responsiveness appreciated!
