### ISSUE TITLE
Introduce a set of scroll-to-end callbacks

### ISSUE THREAD

**Issue by moniuch** [zefoy/ngx-perfect-scrollbar#161]
I was wondering if you could provide callbacks to user's scrolling to an edge of the scrolled container.
That way we could easily:
- enable button "Accept" when user scrolled down to the bottom of the area
- turn on-off `box-shadow` on the neighboring elements to better visually indicate when the container is not at its edge.

I don't have an API ready in my head, just asking.

**Comment by sconix** [comment]
Both of those are already in the library. PS provides events when bottom is reached just check the PS documentation. The box shadow can be enabled by using the scrollIndicators input.
