### ISSUE TITLE
how to use it with lazy modules?

### ISSUE THREAD

**Issue by xmlking** [zefoy/ngx-perfect-scrollbar#162]
Will there be an option to use forRoot() and forFeature() ?

**Comment by sconix** [comment]
There is no need for forRoot and forFeature since this library does not have any services etc. So you use this like any other module with lazy modules.

**Comment by xmlking** [comment]
Well I want to define config at root module level and don’t want to define config in every feature module I want use this model. Will it be posible ?
```
const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};
```

**Comment by sconix** [comment]
Its up to you where you provide the global configuration. You can provide it in your main module but load the PS module in lazy module for example.

**Comment by xmlking** [comment]
Thanks @sconix . Just want to confirm , if I add config to the app module,  same config will be automatically applied to my feature modules that also import PS module but not define config again ?

**Comment by sconix** [comment]
It depends on your setup, you need to get yourself familiar with the Angular provider mechanism. There are many options, you can make a shared config module as well that you import for your feature modules.
