### ISSUE TITLE
Tree Shaking RxJS

### ISSUE THREAD

**Issue by mtraynham** [zefoy/ngx-perfect-scrollbar#164]
It looks like Webpack is adding the entirety of the `rxjs/operators` package from this library.  The only offending line seems to be here:

https://github.com/zefoy/ngx-perfect-scrollbar/blob/master/src/lib/perfect-scrollbar.component.ts#L4

This could probably be changed to:
```ts
import {distinctUntilChanged} from 'rxjs/operators/distinctUntilChanged';
```

Alternatively you could use the popular polyfill method of Observable used by Angular CLI:
```ts
import 'rxjs/add/operator/distinctUntilChanged';
```
And then at https://github.com/zefoy/ngx-perfect-scrollbar/blob/master/src/lib/perfect-scrollbar.component.ts#L77
```ts
    this.stateSub = this.stateUpdate
      .distinctUntilChanged((a, b) => (a === b && !this.stateTimeout))
      .subscribe((state: string) => {
```

I do use portions of the rxjs library with Angular, but this simple line includes the entirety of `rxjs/operators`, which is ~590.47 KB.  Correcting the import reduced that to ~315.55 KB.

**Comment by sconix** [comment]
Hmm tree shaking should remove the others. At least angular-cli production build is not including the whole operators. At least the last time I checked, but I will verify this.

**Comment by sconix** [comment]
At least according to this the way I am using is tree shakeable: https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

Thats the guide I followed when making rxjs part tree shakeable.

**Comment by mtraynham** [comment]
I see what you mean, although adding those plugins seems like a hassle and more maintenance with Webpack.

At the [bottom of that documentation](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#build-and-treeshaking), it alternatively makes the recommendation I proposed, in the section **No Control over Build Process**.  If you use the deep import syntax, the `rxjs/operators` wouldn't have been imported at all, effectively removing the need to tree shake.

> Therefore importing from rxjs/operators will likely make your application bundle larger. However, there's still a way you can use pipeable operators. You will have to use deep imports, similar to how you import prior to version 5.5 and pipeable operators:
>
> ```ts
> import { map, filter, reduce } from 'rxjs/operators';
> ```
> becomes:
>
> ```ts
> import { map } from 'rxjs/operators/map';
> import { filter } from 'rxjs/operators/filter';
> import { reduce } from 'rxjs/operators/reduce';
> ```

**Comment by sconix** [comment]
I quickly tried that and it does not work. The compilation errors out, but I will have another try later and if I get it going I will change it for the next major release. Its true that you said that in this case it would make more sense to just import directly the needed ones but not sure why its not working.

I think that using the plugin makes anyway sense since there might be other libraries that need it and its "standard" plugin when it comes to the Angular. So I dare think different about the current way, but since this is just changing one import line I am fine with the change as long as I get it to work :)

Rollup does not seem to like the suggested import way and I am not expert with rollup so I need to spend bit time to see how to make this work. If you know how to make the change a PR would be nice, but as said I will try to make this change for next major release at the latest (out in a week or two at most).

**Comment by sconix** [comment]
As a side note it seems that they are fixing this issue also by making new rxjs release so that it works out of the box when using Webpack 4.

**Comment by sconix** [comment]
Managed to get it working, in my previous try I had a typo in the rollup config. This change will be in next major release which I release before the end of the month (might be sooner).

**Comment by mtraynham** [comment]
> I quickly tried that and it does not work. The compilation errors out, but I will have another try later and if I get it going I will change it for the next major release. Its true that you said that in this case it would make more sense to just import directly the needed ones but not sure why its not working.

~~I'm not very familiar with rollup either, but after a bit of googling and a few tests, I think I know why. I tried adding the [rollup-plugin-commonjs](https://www.npmjs.com/package/rollup-plugin-commonjs) within the `ngx-perfect-scrollbar-config.umd.js` rollup config and that seems to make the error go away.  **But**, it actually added the source of `distinctUntilChanged` to the output of the umd bundle.  This makes me think that instead `distinctUntilChanged` is not being externalized, which is probably what you'd really want (and the `rollup-plugin-commonjs` should be unnecessary).~~

lol, beat me to it.  Curious, was it because the external mapping had 'rxjs/operator/distinctUntilChanged': 'Rx.Observable.prototype', instead of 'rxjs/operator**s**/distinctUntilChanged': 'Rx.Observable.prototype', (the `s` is missing)

> As a side note it seems that they are fixing this issue also by making new rxjs release so that it works out of the box when using Webpack 4.

That's good to hear!

> Managed to get it working, in my previous try I had a typo in the rollup config. This change will be in next major release which I release before the end of the month (might be sooner).

Awesome, thank you @sconix!

**Comment by sconix** [comment]
Thank you for bringing this to my attention, I had not even noticed this and was in the believe that they already resolved all of these issues with the rxjs 5.5. but seems they did not :) It really should not be the programmers job to know when to use deep path and when not etc.

**Comment by mtraynham** [comment]
@sconix Looks like you've already moved the rxjs imports back to where you expect, but I wanted to add some additional information to this issue.

It is suggested to use imports from the root module which re-exports everything in RxJS 6.  I believe they solve the tree-shaking issue using Webpack's new [`sideEffects: false`](https://github.com/webpack/webpack/issues/6074) flag, per https://github.com/ReactiveX/rxjs/issues/3212.

**Comment by sconix** [comment]
Yes I have already updated the code according to RxJS 6 import guidelines, but yeah good info to be linked here for people using custom webpack setup.
