### ISSUE TITLE
How to avoid footer stick in bottom

### ISSUE THREAD

**Issue by dhanarajp** [zefoy/ngx-perfect-scrollbar#165]
Hi 

I have one scenario need to avoid footer stick in bottom, below is my code stricture

 ```
<header class="HeaderWrapper">
        <router-outlet name="header"></router-outlet>
    </header>
    <perfect-scrollbar style="" [config]="config">
        <section class="ContentWrapper"  >
            <router-outlet></router-outlet>
        </section>
    </perfect-scrollbar>
    <footer class="FooterWrapper">
        <router-outlet name="footer"></router-outlet>
    </footer>

```

**Current behavior:**
Header and Footer always stick in top and bottom.

**Expected behavior:**
Need header always stick in top,  footer based on content should be scroll and if it is content is less than screen then footer should be in bottom of screen.

please suggest to me how to achieve this scenario.

**Comment by sconix** [comment]
This question is not in anyway related to this library. This is normal CSS related question so you might get better luck to get answer in other forums. Most likely you need to use flexbox styles.

**Comment by dhanarajp** [comment]
Yes, i am using flexbox styles, i just know any option available in this library,
Thanks @sconix

**Comment by sconix** [comment]
This library has build in support for angular flex-layout library so if you set perfect-scrollbar to be flex with that it adjust the styles automatically, but if you are just setting flexbox styles manually then you need to style the perfect-scrollbar also.

Although the flex-layout library support just basically adds styles based on fxflex attribute so its possible to "fake" it just by setting the attributes the similar way than flex-layout does to use the existing styles in this library.
