### ISSUE TITLE
psYReachEnd event is fired multiple times when there is no overflow of content

### ISSUE THREAD

**Issue by sosharma1403** [zefoy/ngx-perfect-scrollbar#168]

**Comment by sconix** [comment]
That is actually a bug of perfect scrollbar not of this wrapper. However the next 6.x release of this wrapper has a new way of dealing with the events and will actually also remove the multiple events send issue.

**Comment by sosharma1403** [comment]
by when will v6.x be out?

**Comment by sconix** [comment]
When Angular 6 is out, but today I make a first prelease of it which you can install with the next tag.
