### ISSUE TITLE
How to reference to the directive from typescript?

### ISSUE THREAD

**Issue by ikramcheb** [zefoy/ngx-perfect-scrollbar#170]
I'm using ngx-perfect-scrollbar with my Angular 5 project. I want to scroll the div to top when the route changes.

dashboard.html

 `<div class="main-panel" [perfectScrollbar] #perfectscroll>
     <router-outlet></router-outlet>  </div>`

dashboard.ts

       `
          @Component({
                 selector: 'app-dashboard',
                 templateUrl: './dashboard.component.html',
            })
           export class DashboardComponent implements OnInit {
                @ViewChild('perfectscroll') perfectscroll: PerfectScrollbarDirective;

    ngOnInit() {
        this.router.events.subscribe((evt) => {
            if (!(evt instanceof NavigationEnd)) {
                return;
            }
            this.perfectscroll.scrollToTop()
        });
    }
}`

But I get this error :

> TypeError: _this.perfectscroll.scrollToTop is not a function

when I use this form it works perfectly : 

   `<perfect-scrollbar style="max-width: 600px; max-height: 400px;" [config]="config">
               <div>Scrollable content</div>
    </perfect-scrollbar>`

**Comment by sconix** [comment]
All I can think of is that the first router event comes before the directive is initialized, but then the component should not work neither. Of course there is some change that component vs directive has some effect on the router events order. So you could try registering for the events only in AfterViewInit or wrapping your current setup into timeout.

**Comment by ikramcheb** [comment]
Thanks for the reply. I tried to :
-register for the route events in the AfterViewInit 
-wrap the method into timeout
-both
-call this.perfectscroll.scrollToTop() directly in the AfterViewInit 

Always I get the same error

**Comment by sconix** [comment]
Weird, only thing that comes to mind is that are you sure that you have the latest version of this library?

**Comment by ikramcheb** [comment]
Excuse me if I'm making a dumb mistake.
 In github, you mention that the lastest version is 6.x.x but in [npm registry](https://www.npmjs.com/package/ngx-perfect-scrollbar), the latest release is 5.3.5. (which is the version I am getting when I execute npm update)

I am comfused

**Comment by sconix** [comment]
Yes the 5.3.5 is the latest, the 6.0.0 is to be released really soon so the master has been already updated to reflect that.

You haven't had 4.x version installed? If you have then maybe try re-installing since npm has been known to make weird caching errors. I highly doubt this is the issue, but I start to be out of ideas what could be wrong since the code looks correct to me.

**Comment by sconix** [comment]
In case you left out something from the example code have you tried to use #perfectscroll="ngxPerfectScrollbar" instead of just #perfectscroll? I think this might be your issue that you are not telling Angular that what directive reference you are after.

**Comment by ikramcheb** [comment]
Thank you, that solved my issue 
I added  #perfectscroll="ngxPerfectScrollbar"  And it works perfectly
