### ISSUE TITLE
please provide PageScrollService 

### ISSUE THREAD

**Issue by xmlking** [zefoy/ngx-perfect-scrollbar#171]
please provide   `PageScrollService`  for `scrollXYZ` methods.

some cases (calling from outside `<perfect-scrollbar>`) it would be more convenient to use a `Service` to trigger scrolling 
```
  @ViewChild(PerfectScrollbarComponent) componentScroll: PerfectScrollbarComponent;
```
Example: 
https://github.com/Nolanus/ngx-page-scroll#service

**Comment by sconix** [comment]
I have really hard time understanding why and when service would be more convenient than component / directive reference. So maybe you can elaborate a bit more :)

Since with service you need to tell it what element to scroll so you anyway need to use the element reference.
