### ISSUE TITLE
Change the default colors and transparency

### ISSUE THREAD

**Issue by VaisakhPradeep** [zefoy/ngx-perfect-scrollbar#172]
How can I change the default colors and transparency of the thumb and the rail?  Tried editing the CSS in node modules but no change observed.  Editing within the component by turning off view encapsulation works, but it affects the css of the whole project.  Any help would be appreciated.

**Comment by sconix** [comment]
Thats more of an question to Angular forums, there is nothing special in styling this library, normal Angular / CSS ways work.

**Comment by VaisakhPradeep** [comment]
Thanks for the quick reply.  Sorry for the inadequate question.

**Comment by sconix** [comment]
No worries I leave this open if somebody can help you, but just saying that you might get better luck elsewhere. Have not seen that many answers in these github issues related to basic usage questions.

**Comment by VaisakhPradeep** [comment]
We were able to customize the scrollbar when we used your component separately, instead of installing it as node module.  Thanks.
