### ISSUE TITLE
ReferenceError: window is not defined  (ng-build --aot)

### ISSUE THREAD

**Issue by sagarloona4180** [zefoy/ngx-perfect-scrollbar#173]
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\Sagar\Documents\my-ngccrm\ngccrm-cli\src'
ERROR in C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:132
        return window && document && document.all && !window.atob;
        ^

ReferenceError: window is not defined
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:132:2
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:121:46
    at ./node_modules/style-loader/lib/addStyles.js.module.exports (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:176:88)
    at Object../node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:82:81)
    at __webpack_require__ (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:20:30)
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:63:18
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:66:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)

My Package.json

 "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jquery": "^3.2.11",
    "@types/moment": "^2.13.0",
    "angular2-loaders-css": "^1.0.9",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",
    "jszip": "^3.1.4",
    "moment": "^2.18.1",
    "ng2-bs3-modal": "0.13.0",
    "ngx-bootstrap": "^2.0.3",
    "ngx-perfect-scrollbar": "^4.9.6",
    "ngx-popover": "0.0.16",
    "node-sass": "^4.7.2",
    "npm": "^5.5.1",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.0",
    "@angular/compiler-cli": "^4.3.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "dargs": "^5.1.0",
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-sass": "^1.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.4.0"
  }

**Comment by sconix** [comment]
Are you trying to do server side rendering or? If not then I guess there is some problem in your build setup.

**Comment by sagarloona4180** [comment]
No I am trying server side rendering

**Comment by sconix** [comment]
SSR support was only added for 5.x versions.

**Comment by sagarloona4180** [comment]
but  I am not using SSR

**Comment by sagarloona4180** [comment]
my package.json 


{
  "name": "ngccrm",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --aot  --env=prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jquery": "^3.2.11",
    "@types/moment": "^2.13.0",
    "angular2-loaders-css": "^1.0.9",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",
    "jszip": "^3.1.4",
    "moment": "^2.18.1",
    "ng2-bs3-modal": "0.13.0",
    "ngx-bootstrap": "^2.0.3",
    "ngx-perfect-scrollbar": "^4.5.3",
    "ngx-popover": "0.0.16",
    "node-sass": "^4.7.2",
    "npm": "^5.5.1",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.0",
    "@angular/compiler-cli": "^4.3.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "dargs": "^5.1.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-sass": "^1.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.4.0"
  }
}

**Comment by sconix** [comment]
Then the fault is in your build setup, really hard to say where since the error does not make any sense. Since window should be defined if not doing SSR. That package.json is not showing what build system you are using. If angular-cli then maybe try updating it or re-installing the packages.

**Comment by sagarloona4180** [comment]
yes i am using angular cli 
![image](https://user-images.githubusercontent.com/29095795/37873172-5149f2d8-3034-11e8-8da1-e83b3a373e5d.png)

**Comment by sagarloona4180** [comment]
![image](https://user-images.githubusercontent.com/29095795/37873180-7c02bf8c-3034-11e8-9dba-8d148e6bf29c.png)

**Comment by sconix** [comment]
Then there should not be any other possibilities than buggy cli version or buggy install of packages or some other Windows related bug in the cli or elsewhere. Or I guess one thing known to be causing weird errors sometimes if faulty import paths in the code.

**Comment by sagarloona4180** [comment]
let me reinstall angular cli  and ngx-perfect scrollbar 
which version is good   ngx-perfect scrollbar to install for angular 4

**Comment by sconix** [comment]
The latest 4.x version which can be installed with prev tag (can't remember what was the latest 4.x version released, but the prev tag points to it).
