### ISSUE TITLE
Nested Scrollbar - scrolling both while scroll child on touch screen.

### ISSUE THREAD

**Issue by gauravbhavsar** [zefoy/ngx-perfect-scrollbar#176]
Hello Team,

I have section with fixed height on the page. So, 2 perfect scrollbar one for page and other for section in the page.

But when scrolling inside section of the page (with the mouse click to test scroll on touch screen) and reaching the bottom OR top, the page scroll is also scrolling with the section scroll. And this is the problem.

Below is the sample of html code :
```html
<perfect-scrollbar>
    <mat-card>
        some contents...
    </mat-card>

    <mat-card>
        <perfect-scrollbar> // when scrolling this, parent scrollbar also scrolling
           list of information....
        </perfect-scrollbar>
    </mat-card>

    <mat-card>
        some contents...
    </mat-card>
</perfect-scrollbar>
```

Not able to find any configuration to stop this behaviour.

Posted on stackover flow as well. Please check this [nested-perfect-scrollbar-scrolling-both-the-div-child-as-well-as-parent](https://stackoverflow.com/questions/49486685/nested-perfect-scrollbar-scrolling-both-the-div-child-as-well-as-parent)

**Comment by gauravbhavsar** [comment]
PLease check below gif to find the actual issue.

![nestedperfectscrollbar](https://user-images.githubusercontent.com/5441386/37946681-41cc019a-31a4-11e8-9b12-29af8fdd3220.gif)

**Comment by sconix** [comment]
What version are you using of this library? I haven't noticed that issue in our product and we do have nested scrollbars.

**Comment by gauravbhavsar** [comment]
Thank for reply @sconix 
I am using `version 5.3.5`

In package.json `"ngx-perfect-scrollbar": "^5.3.5",`

I am facing problem in touch screen, it is working nice with mouse wheel.

**Comment by sconix** [comment]
Ok, I try to verify / check this as soon as possible before the week is over for sure.

**Comment by sconix** [comment]
Sorry that this has taken some time, but I now remembered that perfect-scrollbar removed the touch propagation support so I wonder if this is due to that.

Are you using the component or directive? If you are using the component you could try setting the autoPropagation that also controls the touch propagation. What it does is that it tries to be bit smarter about the propagation, i.e. if you scroll / swipe to the end quickly it does not yet propagate the event to the parent only after you start scrolling/swiping again after a small delay it propagates the event to the parent. This should avoid annoying parent scrolling when you only wanted to scroll the child until the end.

**Comment by gauravbhavsar** [comment]
Thank to reply @sconix 

>Are you using the component or directive?

I am using component.
I added autoPropagation and it's working awesome.

> if you scroll / swipe to the end quickly it does not yet propagate the event to the parent only after you start scrolling/swiping again after a small delay it propagates the event to the parent. This should avoid annoying parent scrolling when you only wanted to scroll the child until the end.

Yes, I noticed the delay, but I wonder if the delay would be more smaller.

Thank you.

**Comment by sconix** [comment]
For the next release I might do it so that you can configure the delay. The next major release which is out with Angular 6 is also better optimized regarding change detection. The events cause change detection at the moment so the delay might feel longer that it actually should be.

**Comment by gauravbhavsar** [comment]
It would be great, Thanks again.

**Comment by webdevan** [comment]
@sconix, I'm having the same problem except I am using the directive. Is it possible to use autoPropagation on the directive somehow?

**Comment by sconix** [comment]
No since the directive is the "pure" implementation of perfect-scrollbar it does not add any functionality or styling on top of the perfect-scrollbar. So you need to use the component if you want to use the extra functionality.

**Comment by webdevan** [comment]
Ok, so is the touch double scrolling bug in perfect-scrollbar itself then? It's not a bug in ngx-perfect-scrollbar?

Side note: The reason I don't use the component is because it loads the ps stylesheet which I don't want. It would be a nice feature if one could disable/configure the component's default stylesheet.

**Comment by sconix** [comment]
Its more of a feature than bug, perfect-scrollbar does not provide means to control touch propagation so you need to do it yourself. You can just catch the touch event from the child scroll areas and stop the event propagation thats what the component does. Its no magic just normal events handling :)

The component does have usePSClass input that can be used to prevent adding of ps class to the main element which is needed for the default styles to take effect. It naturally wont prevent loading of the default stylesheet, but should prevent them having any effect when you can provide your own styles.
