### ISSUE TITLE
Is there any way to show ngx-perfect scrollbar when we focus out from from scrollbar section 

### ISSUE THREAD

**Issue by sagarloona4180** [zefoy/ngx-perfect-scrollbar#179]

**Comment by sconix** [comment]
You can always modify the styles to show the scrollbars always.

**Comment by sconix** [comment]
I plan adding some sort of input or extra class for 6.1 release that would allow enabling always showing scrollbars without custom CSS.

**Comment by sconix** [comment]
There is now support in the component styles that when adding class ps-show-always to the component that the scrollbars area shown all the time.
