### ISSUE TITLE
Scrollbar displays only on mouse wheel scroll

### ISSUE THREAD

**Issue by jeevasusej** [zefoy/ngx-perfect-scrollbar#181]
Hi,

If we have more content at the initial stage, the scroll bar appears when entering into the scroll area.

But at the initial stage, there is no more content. Then we dynamically adding the content to the scrollable area. 
Now the scrollbar does not appear when hovering into the scroll area.
We need to use the mouse wheel to appear the scroll. Then after this, we can see the scrollbar on mouse hover.

**Comment by sconix** [comment]
You need to call the update if content is dynamically altered. The component has automatic update function that works in most cases, but when using directive you need to take care of calling update manually.
