### ISSUE TITLE
Can't resolve 'rxjs/Subject' with "rxjs": "^6.0.0"

### ISSUE THREAD

**Issue by tiagorvs** [zefoy/ngx-perfect-scrollbar#182]
ERROR in ./node_modules/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/****/node_modules/ngx-perfect-scrollbar/dist'

angular: 6.0.0-rc.5
ngx-perfect-scrollbar: 5.3.5
rxjs: 6.0.0

**Comment by tiagorvs** [comment]
Works fine with 6.0.0-0

**Comment by sconix** [comment]
Yeah, I am making next pre release next week but as you found out the -0 should work fine as well.
