### ISSUE TITLE
Can't resolve 'rxjs/Subject' in angular/cli 6.0

### ISSUE THREAD

**Issue by TopDuke** [zefoy/ngx-perfect-scrollbar#184]
ERROR in ./node_modules/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'D:\\****\node_modules\ngx-perfect-scrollbar\dist'

angular/cli : 6.0.0
ngx-perfect-scrollbar: 5.3.5

**Comment by mizio85** [comment]
same error after update to angular 6

**Comment by RainingNight** [comment]
+1

**Comment by sconix** [comment]
You need to use the 6.x version of this library with Angular 6. There is one pre-release out with @next tag and I should be able to get the final 6.0.0 release out within this week.

**Comment by mizio85** [comment]
@sconix it works perfectly, thanks

**Comment by daddyschmack** [comment]
happening again after upgrading to v7
ERROR in ./node_modules/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/Users/xxx/Projects/xm-web/node_modules/ngx-perfect-scrollbar/dist'

**Comment by sconix** [comment]
You need to check your npm installation. There has been no breaking changes in Angular 7 so the latest version of this library works normally.
