### ISSUE TITLE
Mouse wheel scrolling works only when mouse hover scrollbar.

### ISSUE THREAD

**Issue by baio** [zefoy/ngx-perfect-scrollbar#188]
Hi.

Mouse wheel scrolling works only when mouse hover scrollbar, is it intended behavior ? If so is there way to override this behavior ?

Thanks.

**Comment by sconix** [comment]
Thats not the case in the example app if you check it. Or if it then can you tell me what your browser is?

If the example app works then you most likely have something in the scroll area that is capturing mouse wheel events and therefore they are not reaching the perfect-scrollbar.

**Comment by baio** [comment]
Sorry, this one was incorrect question. The problem was - I have a tree of elements and for each node content I initialized perfect-scrollbar, so problem was resolved with `[disbaled]="!isRootElement"`
