### ISSUE TITLE
Object is not a function...

### ISSUE THREAD

**Issue by freserovski** [zefoy/ngx-perfect-scrollbar#189]
Hi, i received following error:
TemplateListComponent.html:5 ERROR TypeError: Object(...) is not a function
    at eval (ngx-perfect-scrollbar.es5.js:613)
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at NgZone.runOutsideAngular (core.js:4708)
    at PerfectScrollbarComponent.ngOnInit (ngx-perfect-scrollbar.es5.js:611)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)

the method which goes bad is :  
` this.zone.runOutsideAngular(function () {
                var /** @type {?} */ element = _this.directiveRef.elementRef.nativeElement;
                fromEvent(element, 'wheel')`

Does anybody have same problems when using component? Angular 5.2.10

**Comment by zorahrel** [comment]
+1

**Comment by sconix** [comment]
What is your ngx-perfect-scrollbar / rxjs version? That sounds like the error is coming from the fromEvent call.

**Comment by Eugeny** [comment]
fromEvent is an operator in the latest RxJS

**Comment by Eugeny** [comment]
Temporary fix:

```ts
import { fromEvent } from 'rxjs/internal/observable/fromEvent'
import { merge } from 'rxjs/internal/observable/merge'
require('rxjs').fromEvent = fromEvent
require('rxjs').merge = merge

**Comment by freserovski** [comment]
hi, we have just use "5.3.5" version and it works without problems...

**Comment by sconix** [comment]
The latest 6.x version is mainly meant for Angular 6 so it uses rxjs 6. So most likely if you want to use it with Angular 5 you need to use rxjs and rxjs-compat 6.x packages instead of rxjs 5.

**Comment by Eugeny** [comment]
The error is happening for me with Angular 6 + RxJS 6 too, but I don't have rxjs-compat installed.

**Comment by sconix** [comment]
Compat package is not needed when using 6.x versions. I would try fresh npm install. We don't have any issues and the example app works also and it uses angular 6 etc.

**Comment by mguthrie88** [comment]
I had this issue when running Angular 5, and I had installed ngx-perfect-scrollbar 6.x, downgrading with the following commands resolved the issue for me:
` npm remove ngx-perfect-scrollbar`
`npm install --save ngx-perfect-scrollbar@^5.0.0`

**Comment by arunmeanssun** [comment]
@freserovski  . ..  your solution worked great  . .  for angular 5 version, scrollbar 5.3.5 works fast and error got fixed

**Comment by c-moreno** [comment]
@mguthrie88 works sweet, thansk!
