### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by castamir** [zefoy/ngx-perfect-scrollbar#19]
build has many errors... this is my working tsconfig.json:

```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "sourceMap": true,
    "target": "es6",
    "lib": ["dom", "es6"],
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "node"
    ],
    "exclude": [
      "node_modules",
      "../node_modules",
      "../dist"
    ]
  },
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true
  }
}
```

see http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/

also remove `>/dev/null` from package.json build command - its not cross platform compatible

**Comment by sconix** [comment]
Thanks, I will make those changes for next release.

**Comment by sconix** [comment]
Do you know what is the actual fault in my current tsconfig? Since I don't see any important difference in yours and mine should be pretty much what angular documentation and official packages use.

**Comment by sconix** [comment]
I updated the build scripts to not use cp and >/dev/null, let me know if there is still problems on Windows. I don't have access to a Windows PC, our whole company is Linux/OSX only.

**Comment by castamir** [comment]
problem is in loading duplicate type definitions from `core-js`, see link above for explanation and solution

errors like
```
node_modules/@types/core-js/index.d.ts(21,14): error TS2300: Duplicate identifier 'PropertyKey'.
```

**Comment by sconix** [comment]
Ok, I just don't get why something thats not included should be excluded i.e. what is trying to include that. Anyway I removed the core-js types since they are not needed.

**Comment by sconix** [comment]
I assume that this is also fixed now when I removed core-js types. Let me know if not and I fix the remaining issues.
