### ISSUE TITLE
Content not visible - possible change detection failed

### ISSUE THREAD

**Issue by MikeDabrowski** [zefoy/ngx-perfect-scrollbar#191]
Angular 4.4.4, Zone disabled, manually running change detection by calling zone.run();

Scrollbar works surprisingly well but after first init, content is not visible. I can highlight and copy paste somewhere but can't see content and highlight. In devtools I see that the content is there. I couldn't fix it with css. Only scroll to bottom, which in my case triggers zone run, helps. Content is loaded from variable, I assing string to variable in zone.run. 

I also tried to call update() on directiveRef but it does nothing.

```html
<div [class.fade]="!scrolledDown" *ngIf="rodoInfo">
    <perfect-scrollbar [config]="PERFECT_SCROLLBAR_CONFIG" (psYReachEnd)="reachedEnd()" #ps>
        <div [innerHtml]="rodoInfo"></div>
    </perfect-scrollbar>
</div>
```
```typescript
...subscribe((data)=>{
    this.zone.run(()=>{
    ....
    if (value.clauseItems) {
            this.zone.run(() => this.rodoInfo = value.clauseItems[0] && value.clauseItems[0].content);
            this.zone.run(() => {this.ps.update()});
          }
    });
});
```

I doubt anyone faced such issue, but maybe someone has an idea.

**Comment by kgrvr** [comment]
Yup same thing happened with me. One thing that I noticed is that it works when you press any key on keyboard or on mouse. Pressing any key binds the data to the UI.

**Comment by chiragdev8062** [comment]
Any solution on this ?

**Comment by chiragdev8062** [comment]
@MikeDabrowski & @kgrvr did you got any solution for this ?

**Comment by MikeDabrowski** [comment]
@chiragdev8062 
Im sorry but no. It's been years. I'm no longer in that project and I don't know how it ended up.
Mind that it was in 4.4.4 so your case may not apply or might be resolved by now, see it was closed as 'completed'

**Comment by chiragdev8062** [comment]
@MikeDabrowski thanks for replay
you are right but getting same problem thats why I asked. currently I’m working with angular 12 and ngx-perfect-scrollbar 9.0.0
