### ISSUE TITLE
Question: How to create Custom Attribute Directive extends from PerfectScrollbarDirective?

### ISSUE THREAD

**Issue by lkovari** [zefoy/ngx-perfect-scrollbar#193]
Hi All,

I would like to get some help, how can I create on correct way Custom Attribute Directive extends from PerfectScrollbarDirective?

import { PerfectScrollbarDirective, PerfectScrollbarConfig,PerfectScrollbarConfigInterface, PERFECT_SCROLLBAR_CONFIG } from 'ngx-perfect-scrollbar';
import { Directive, ElementRef, KeyValueDiffers, NgZone, Optional, Inject, PLATFORM_ID } from '@angular/core';
@Directive({
    selector: 'ul.ui-container'
})
export class ContainerScrollbarDirective extends PerfectScrollbarDirective {
    static psConfig = <PerfectScrollbarConfig>{
        suppressScrollX: true
    };
    constructor(private zon: NgZone, private dfs: KeyValueDiffers,
        public elRef: ElementRef, @Inject(PLATFORM_ID) private pltfId: Object,
        @Optional() @Inject(PERFECT_SCROLLBAR_CONFIG) private def: PerfectScrollbarConfigInterface) {
        super(zon, dfs, elRef, pltfId, ContainerScrollbarDirective.psConfig);
    }
}

**Comment by sconix** [comment]
This question is not really related to this library since its more of an Angular related question so you most likely have more luck by asking in Stackoverflow or some other Angular forum.
