### ISSUE TITLE
Scrollbar in ipad

### ISSUE THREAD

**Issue by MtarantoOa** [zefoy/ngx-perfect-scrollbar#195]
Hello guys,

We are using the library in our angular 5 application.

The problem we are facing is that for some resolutions we set the max-height in none:

```
@media (max-width:1030px){
    .scrollable-documents-content, .scrollable-events-content{
        max-height: none;
    }
}
```

But when we see the app in we get bunch of errors:

![image](https://user-images.githubusercontent.com/31453863/42328755-7e0aca48-8045-11e8-8a93-7e0ece3839f3.png)

I suppose that is because we set the max-height to none and there is nothing to scroll.

My question is:

There is a way to disable the perfect scrollbar on some resolutions? 

Thanks for your help!

**Comment by sconix** [comment]
Scroll area always needs height. If you don't need the perfect-scrollbar then you can always set it to disabled and then no perfect-scrollbar is loaded.

But I don't quite get the idea, if there is nothing to scroll there is no scrollbars so what is the point of max-height none? If you are just looking for way to disable perfect-scrollbar on mobile then the disabled attribute is the way to go.

**Comment by MtarantoOa** [comment]
@sconix  Thanks for your answer.

Can you provide an example of how to do this? I was not able to find on the home page.

```
<perfect-scrollbar class="scrollable-documents-content">
    <table>
        <tbody>
            <tr>
                <td>1</td>
            </tr>
            <tr>
                <td>2</td>
            </tr>
            <tr>
                <td>3</td>
            </tr>
            <tr>
                <td>4</td>
            </tr>
            <tr>
                <td>5</td>
            </tr>
            <tr>
                <td>6</td>
            </tr>
        </tbody>
    </table>
</perfect-scrollbar>
```

I should add the disabled  on the perfect-scrollbar element?


Thanks!

**Comment by sconix** [comment]
Yes, its mentioned in the readme.

**Comment by MtarantoOa** [comment]
Ok, 
should be something like this:

`<perfect-scrollbar class="scrollable-policies-content" [disabled]="true">`


Correct?

**Comment by sconix** [comment]
Yes, that disables loading of the perfect-scrollbar so the element acts like normal div.
