### ISSUE TITLE
Angular animation issue - content gets "scrolled" to top

### ISSUE THREAD

**Issue by lorado** [zefoy/ngx-perfect-scrollbar#197]
I am using the wrapper in angular 6. Just added angular animations to my project, and got a little trouble...

In my code I use ngSwitch to display/hide particular views. Here is an overview of my Code:

```html
<ng-container [ngSwitch]="currentChatPage">
    <div [@listAnimation] *ngSwitchCase="SessionChatPage.List">
        <perfect-scrollbar>...</perfect-scrollbar>
    </div>
    <div [@chatAnimation] *ngSwitchCase="SessionChatPage.Group">
        <perfect-scrollbar>...</perfect-scrollbar>
    </div>
    <div [@chatAnimation] *ngSwitchCase="SessionChatPage.OneOnOne">
        <perfect-scrollbar>...</perfect-scrollbar>
    </div>
</ng-container>
```

So without animation there is only 1 `div` with perfect scrollbar visible. Now I added intuitive animation like on iOs. So I have a list with chats, when I click on chat, then **SessionChatPage.List** gets animated to the left with `translateX(-100%)`, and the **SessionChatPage.Group** or **SessionChatPage.OneOnOne** gets animated from the right to the visible position: `translateX(100%)` -> `translateX(0)`. 

And here is the Problem: When animation begins the transition, perfect-scrollbar seems to be destroyed... at least the content-container in perfect-scrollbar loses `.ps` class, so that the container loses height limitation, and so loses scroll, and so it "jump" to the top.

How can I handle this problem? Any suggestions?

Take a look at the [video I made](https://www.youtube.com/watch?v=KbFYsTOJVkY). I first remove the ps class from element, to imitate what happens. And then with animation. I slowed the animation duration, so it is possible to see, what happens.

**Comment by lorado** [comment]
Ah lol... I think I found the base of the problem... https://github.com/angular/angular/issues/19826

I already thought, that it should be a lifecycle problem with ngdestroy... just found that issue. Well... anyway, can I somehow solve my problem? =)

**Comment by sconix** [comment]
Not really related to this wrapper, more of an question to Angular forums, but I guess one way is to trigger the animation with animation state variable and only change the currentChatPage after the transition is done.
