### ISSUE TITLE
How to use in a lazy loaded module?

### ISSUE THREAD

**Issue by sclausen** [zefoy/ngx-perfect-scrollbar#2]
Can't use it in an lazy loaded module, since it's not allowed to put `PerfectScrollbarModule` in a SharedModule and if I import it in the AppModule, the element `perfect-scrollbar` isn't a known element.

**Comment by sconix** [comment]
I haven't used lazy loading yet, so can't help you right away. Can you make a Plunker example etc. about your problem? Then I could have a look and see what is going on.

When importing in AppModule do you also export it?

**Comment by sclausen** [comment]
At first, here is a working plunker of your example: http://plnkr.co/edit/E286oz?p=preview

**Comment by sclausen** [comment]
Here is a plunkr, demonstrating the problem: http://plnkr.co/edit/20Sraq?p=preview
EDIT: Here is a better demonstration, where a not lazy loaded component has a working perfect-scrollbar and the lazy loaded component won't load: http://plnkr.co/edit/Cv5ibD?p=preview

**Comment by sconix** [comment]
Thanks for the examples, now I remember why the module loading is only allowed in app module :) It was only supposed to be temporal and I was going to add the forChild method as well for loading the module in lazy modules. I will release 0.9.0 soon where this has been fixed.

**Comment by sconix** [comment]
This is now fixed in 0.9.0, let me know if you still have problems.

**Comment by sclausen** [comment]
@sconix works like a charm ;)

**Comment by breadadams** [comment]
How does this work? I've tried importing in main AppModule and i'm getting a `'perfect-scrollbar' is not a known element` error.

Importing in my SharedModule fixes it, but maybe I'm just doing something wrong? 🤔

**Comment by sconix** [comment]
Just like any other module there is nothing special in this module. So if you import in a module and use it in other then you need to export it as well. Other than that it does not matter if you use it lazy loaded module or none lazy loaded there is no difference in the usage.
