### ISSUE TITLE
Example not working in IE11 and Firefox

### ISSUE THREAD

**Issue by castamir** [zefoy/ngx-perfect-scrollbar#20]
IE11 has a Syntax error shown in console and FF looks like this:

![2017-01-31_145934](https://cloud.githubusercontent.com/assets/1245190/22467709/f0d0e0d6-e7c5-11e6-9e48-22af02d4e937.png)

**Comment by sconix** [comment]
I will fix the example for the next release. I know that Firefox needs some special flexbox stuff to work, but did not know that IE11 needs it as well.

**Comment by sconix** [comment]
I added fix for the Firefox, but don't have access to IE11 so if you could test it would be nice. Or did you mean the the layout problem was only with Firefox and IE11 has some console errors? Can you paste the errors here so I could look into possible cause. Hard to think anything so special in the example that it would cause errors.

**Comment by castamir** [comment]
I'll try your example and then adding your component into my project and let you know (it may take a while, I have other things to do right now)

**Comment by sconix** [comment]
Ok, no hurry. I will gladly fix the example for Firefox / IE11 if there are still problems.

**Comment by castamir** [comment]
Right now, IE11 has similar problem like FF had...

![2017-02-03_091249](https://cloud.githubusercontent.com/assets/1245190/22584156/276c75b0-e9f1-11e6-85f6-adb1008da933.png)

**Comment by sconix** [comment]
Ok, I guess I need to fire up a virtual machine so that I can find out what flexbox magic works for all or maybe I just add using of angular/flex-layout library, I would hope that it can take different browsers in account.

**Comment by PetaPetaPeta** [comment]
I am also very interested in getting this bug solved. Let me know if you need any help testing what you come up with.

**Comment by sconix** [comment]
Well I don't think there is a bug in the library itself or its styles. Its most likely the flexbox styles of the example, but lets see. There might be of course some style tweaks to be done for the lib so that it plays nicer with flexbox but that is to see. I try to fix this today.

**Comment by sconix** [comment]
I have now updated the example app to use angular flex-layout library so if someone could test it with IE11 I would be grateful. At least now without any style tweaks it works in Chrome and Firefox so I am really hopeful that it works in IE11 as well. If not then I need to start setting up some virtual machine with Windows.

Just make sure that the example is not loaded from cache etc. and please use this url: https://zefoy.github.io/ngx-perfect-scrollbar/ I did not push the code yet.

**Comment by PetaPetaPeta** [comment]
I've tested with IE11 on Windows 10, 8.1, and 7. It was working on all versions.

Thank you very much for this quick response on this!

**Comment by sconix** [comment]
Ok, thanks a lot! We have slowly moved to using @angular/flex-layout library in our other projects and so far it looks really nice, no need to spend time to find styles that all browsers are happy with / use own layout class system.

**Comment by PetaPetaPeta** [comment]
It does however seem to be misbehaving on IE10 now. I don't know if this is an entirely different issue though.
![bs_win7_ie_10 0](https://cloud.githubusercontent.com/assets/2445709/22595183/9986dd54-ea26-11e6-9b39-26b1ab399010.jpg)

I'm not getting an error in the console though.

**Comment by castamir** [comment]
alngular/fle-layout does not support IE10 see https://github.com/angular/flex-layout#browser-support

**Comment by sconix** [comment]
I don't support IE10 neither, neither should anybody since its support has ended by MS. Specially not for the example app.
