### ISSUE TITLE
Noob question after changing CSS

### ISSUE THREAD

**Issue by michaelchanSUG** [zefoy/ngx-perfect-scrollbar#200]
Trying out this component successfully in Angular 6. However I want to change the look of it.

I can find and change the css file under /dist/lib/*.css  but what else do I need to do in order for change to take effect?

Thank you

**Comment by sconix** [comment]
Your question is not related to this library. You need to study how to style components in Angular. So asking in Angular related forums might get responses more easily.

**Comment by michaelchanSUG** [comment]
Just to wrap this up in case somebody else has similar question.

I ended up doing
1. override certain css class in local component's css
2. use ViewEncapsulation.None
3. prioritize the local modified css with "body" selector (hence "body .ps__thumb-y"

Works but not the solution I was looking for. I was looking to replace the style by stylesheets loading order yet still can't find the proper way to do it in Angular 6.
