### ISSUE TITLE
ERROR in : Can't bind to 'perfectScrollbar' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by Kalpb** [zefoy/ngx-perfect-scrollbar#203]
Hi,
I installed the module and provided the global configurations in app.module.ts
In HTML i used
```
<div class="ps" style="position: relative; max-width: 600px; max-height: 400px;" [perfectScrollbar]="config">
  <div>Scrollable content</div>
</div>
```

but when i execute the application i get following error
```
ERROR in : Can't bind to 'perfectScrollbar' since it isn't a known property of 'div'.
```

Can you please help?

**Comment by sconix** [comment]
You should try Angular forums for help regarding Angular usage, issues are reserved mainly for bugs and library related problems. You get that error if you have not imported the module.

**Comment by Kalpb** [comment]
Fixed the issue,
Had to import PerfectScrollbarModule in shared.module.ts.

Thanks :)
