### ISSUE TITLE
Middle mouse button does not work

### ISSUE THREAD

**Issue by viters** [zefoy/ngx-perfect-scrollbar#204]
Cannot trigger middle mouse click over container with perfect scroll bar

![image pasted at 2018-8-21 12-18](https://user-images.githubusercontent.com/13100466/44396456-3aa0b980-a53d-11e8-9a33-3b9a796457b9.png)

**Comment by sconix** [comment]
With component or directive or both?

**Comment by viters** [comment]
@sconix 
Both. I am testing on https://zefoy.github.io/ngx-perfect-scrollbar/

**Comment by sconix** [comment]
So then its an issue with the perfect-scrollbar and not with this wrapper. Since the directive is kind of pure perfect-scrollbar implementation, there is no additional events handling so the issue must be in the perfect-scrollbar itself.

**Comment by earshinov** [comment]
For information, here is the relevant ticket in perfect-scrollbar:
https://github.com/utatti/perfect-scrollbar/issues/412

It is not going to be implemented. Ever.
