### ISSUE TITLE
Rail does not retain longer width if click is active but hover is not

### ISSUE THREAD

**Issue by aks1994** [zefoy/ngx-perfect-scrollbar#205]
As you can see in GIF from the demo, the rail reverts back to the shorter width when not hovering over it but the thumb retains its longer width if click is active.

I worked around this by adding the css style `.ps--clicking.ps__rail-y{width:15px!important}` but think this is a bug. The same issue is not present in perfect-scrollbar, only in this ngx version.

![perfect scrollbar bug](https://user-images.githubusercontent.com/30187636/44460374-71a0c900-a62a-11e8-94bf-c61ae7e68748.gif)

**Comment by sconix** [comment]
Yes its a bug in the styles, thanks will fix for next release.
