### ISSUE TITLE
load paginated scroll with ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by beingbing** [zefoy/ngx-perfect-scrollbar#206]
I am building a desktop chatting application with electronJS and angular5, I am using ngx-perfect-scrollbar in scrolling chats. It worked perfectly until I introduced pagination for old messages, I want to load old messages when user scrolls to top(i.e., scrolls down) (just like slack), is there any way to do that with ngx-perfect-scrollbar ?

**Comment by sconix** [comment]
Not fully sure if I understand but there is the reach events that you can use when the scroll area reaches top / bottom etc.

**Comment by beingbing** [comment]
well, simply put, my problem is, after preparing new content, I need to take my scroll to a particular message with a given messageId

**Comment by sconix** [comment]
I still don't see what the problem is, you have the means to scrollTo and the reachEnd events so those should be more than enough if I understand the problem. And getting the scroll position to scroll to is normal JS there is no magic needed :)
