### ISSUE TITLE
Get scroll distance from top

### ISSUE THREAD

**Issue by mishotek** [zefoy/ngx-perfect-scrollbar#207]
Hello, after digging in the documentation I still could not figure out how to subscribe to the scroll event on perfect scrollbar. Can someone please provide a working example of logging the scrolled distance from top. Thanks in advance. This is an example of what I want to achieve: 
`<perfect-scrollbar (onScroll)='distanceFromTop => console.log(distanceFromTop )'>`
`<router-outlet></router-outlet>`
`</perfect-scrollbar>`

**Comment by sconix** [comment]
From the readme:

position(absolute)                     // Returns the reach or absolute scroll position.

**Comment by mishotek** [comment]
And what should I do in case of a component, not a directive?

**Comment by mishotek** [comment]
A very basic example would be very appreciated

**Comment by sconix** [comment]
Readme and example app has those information as well :) Since the example app is a very basic example of all the basic features.

**Comment by mishotek** [comment]
I have checked demo app, I'm logging the even object to scroll, but this object doesn't seem to have a scroll distance property. I've tried calling .position() on both event and the reference to the scrollComponent, but neither of them has such function or property.

**Comment by sconix** [comment]
So can you then explain that what values you are after? The position function returns top and left values i.e. the absolute scroll position. The other option is that you are after the geometry values, check the geometry() function.

**Comment by mishotek** [comment]
On what should I call position? On event or the reference?

**Comment by mishotek** [comment]
This is the scrollbar
`
<perfect-scrollbar class="scroll-container scroll-container--position" (psScrollY)="onScrollEvent($event)" [config]="{suppressScrollX: true}">
      <router-outlet></router-outlet>
    </perfect-scrollbar>`
In .ts file: 
`@ViewChild(PerfectScrollbarComponent) componentRef?: PerfectScrollbarComponent;`

`public onScrollEvent(event: any): void {`
`      console.log(event.position);`
`      console.log(this.componentRef.position);`
`      console.log(this.componentRef.position());`
` }`
On scroll I'm getting this log:
undefinded
undefinded
this.componentRef.position is not a function

So how should I call .position()?

**Comment by sconix** [comment]
As I said its mentioned in the README and there is an example in the example app how to call the functions.

**Comment by mishotek** [comment]
For other people who might be interested in an answer, after digging in the implementation I found a solution: 
1) Get the reference to the component like in demo app
`@ViewChild(PerfectScrollbarComponent) componentRef?: PerfectScrollbarComponent;`
2) Get a directive reference from the component reference:
`this.componentRef.directiveRef`
3) Now you can call position on the directive reference:
`console.log(this.componentRef.directiveRef.position(true));`
