### ISSUE TITLE
Doesn't work properly with fixed element.

### ISSUE THREAD

**Issue by technbuzz** [zefoy/ngx-perfect-scrollbar#210]
I have searched through other issues where it's said if something is fixed than how and why we should have a scrollbar. 

But in my case of using clarity vertical nav, the sidebar should be fixed. Although the sidebar is fixed but I get this white space as you can see in the screenshot below. If I try to add some css like ```height:100%``` than I get the default sidebar.

![image](https://user-images.githubusercontent.com/1523391/45802030-b3bf3800-bcc6-11e8-822f-cea4ee9cab80.png)

**Comment by sconix** [comment]
Sorry I do not get the problem. Scroll areas need to have height defined to work if you are only wondering why height 100% is needed.
