### ISSUE TITLE
psYReachEnd triggered on Init, window resize, display: block/none

### ISSUE THREAD

**Issue by Oleg-Sulzhenko** [zefoy/ngx-perfect-scrollbar#212]
I'm enable to complete lazyLoading for list of items im modal, because psYReachEnd triggered unespected when display block for modal add and on window resize if content height is smaller than scroll area, also on init - this is strange behaviour and i think this is a BUG.

**Comment by sconix** [comment]
I have not noticed that kind of behavior so at least in our applications the psYReachEnd event is working as it should. So maybe you can make a Stackblitz reproduction of the problem so I can have a look. Anyway most likely its a Perfect Scrollbar bug and not related to this library.

**Comment by Vaibhav2812** [comment]
For me also it's firing initially without scroll. i am using directive perfect scrollbar

**Comment by chiragdev8062** [comment]
@sconix got same problem, `psYReachEnd` is called automatically without reached to the bottom of div (on page load).

**Comment by sconix** [comment]
Unfortunately this library is not maintained anymore as mentioned on the frontpage since there are better options nowadays.

**Comment by cfoxy17** [comment]
All you have to do is this

`     
onScrollToBottom(event) {
		**if(event.target.scrollTop == 0) {**
			return;
		}

                ... <your code for what to do after scrolling to the bottom>
`

HTML:
`
 <perfect-scrollbar (psYReachEnd)="onScrollToBottom($event)">
`
