### ISSUE TITLE
Scroll bar creating an issue with router outlet

### ISSUE THREAD

**Issue by droidtechnician** [zefoy/ngx-perfect-scrollbar#213]
My current project is in Angular 6,
When I place a router-outlet inside the perfect-scrollbar component selector. This is not rendering the perfect-scrollbar infact showing the normal scroll bar but when I wrap the entire html into the perfect-scrollbar component. Then it is showing the scrollbar

`    <perfect-scrollbar [config]="scrollBarConfig">
        <div class="content">
            <router-outlet></router-outlet>
        </div>
    </perfect-scrollbar>
`

**Comment by sconix** [comment]
Perfect scrollbar needs to have specific height just like any scroll area. So you need to style it so that its height is correct. The default height style 100% does not work in all cases. So just define the height correctly and it should work.
