### ISSUE TITLE
How to check if scrolled

### ISSUE THREAD

**Issue by RomaHL** [zefoy/ngx-perfect-scrollbar#214]
Is it possible to catch if perfect-scrollbar container scrolled to bottom and how many pixels are scrolled?

**Comment by sconix** [comment]
Yes see the README about reach events / position api call.

**Comment by RomaHL** [comment]
Can you give me a example, becouse a cannot understand how implement it.

**Comment by sconix** [comment]
There is an example app that has an example of how to call functions and for events well they work like any other event in Angular so you just add (psYReachEnd)="scrolledToBottom()". The geometry function can be used to get the size of the scroll container and position gives you scrollTop and scrollLeft values. With those numbers you know at what position the scroll is.
