### ISSUE TITLE
Dynamic Settings and PS Events

### ISSUE THREAD

**Issue by heyepe** [zefoy/ngx-perfect-scrollbar#215]
Thanks for the great library @sconix

We've run into unexpected behavior that may be a bug. This behavior occurs after making changes to the config object and manually trigger angular change. When the change detection has completed, the PS events stop firing. Using the code snippet below as an example, function loadMore() is called successfully up until we change the wheelSpeedVar and run detectChanges(). loadMore() stops firing BUT the new wheelSpeed value is reflected in the component.

**Ex.**
<perfect-scrollbar  class="flex-item container" (psYReachEnd)="loadMore($event)" [config]="{wheelSpeed: wheelSpeedVar}">
    <div>...</div>
</perfect-scrollbar>

Any ideas how to we might achieve the desired effect of accessing PS events after dynamically updating the config settings?

Thank you very much for the insight!

**Comment by sconix** [comment]
Sounds strange, I need to test / look into this next week when my holiday is over. Have you tried changing some other config option than wheelSpeed? That would tell if the problem is in PS with wheelSpeed option or if its in this wrapper.

**Comment by heyepe** [comment]
Thank you for the quick response @sconix. Yes, we've tried changing a number of the other config variables with the same result I outlined above. 

Apologies for interrupting your holiday!

**Comment by sconix** [comment]
I could not replicate this in any way. And I must say that this sounds really strange and something that would be bug in Angular more than in this library. What Angular version do you have? And is there anything else changing at the same time when you change the config like styles etc.

**Comment by heyepe** [comment]
fixed when we updated from v6.3.1 to v7.1.0. Thank you
