### ISSUE TITLE
Document the domain of helper methods

### ISSUE THREAD

**Issue by IlCallo** [zefoy/ngx-perfect-scrollbar#217]
Hi zefoy, wounderful work you did here :)
One little problem: I found myself in need of digging into the source code to understand which kind of values were accepted from the helper methods.

Eg. it's not immediately clear if the `scrollToX` offset parameter is in pixel or what (even when checking from the demo project code), same for the speed.
Is it possible to add some kind of annotation?
In my case I just kept trying random numbers until I understood which was the domain you were expecting but I guess it's easy to just specify if we are talking about milliseconds, pixels, percentage etc...

**Comment by sconix** [comment]
I try to improve the readme, imho the used units are rather common in these contexts so it should be rather obvious what they are, but there is no harm mentioning them in the readme.

**Comment by IlCallo** [comment]
Thank you kind sir 👨🏻‍💼
