### ISSUE TITLE
How to detect the mousedown event?

### ISSUE THREAD

**Issue by r0manchak** [zefoy/ngx-perfect-scrollbar#219]
Hi,
First of all, thanks for such a laborious work on this plugin.

Is it possible to somehow detect the `perfect-scrollbar` `mousedown` event?

Both whole `ps-content` and particularly `y-rail` event detection would be helpful.

PS. I need this event to preven dropdown being closed when a mouse stops outside of the container.

Many thanks, 
Andrii

**Comment by sconix** [comment]
Why don't you just add your own element inside the perfect-scrollbar and catch the event from that?

**Comment by r0manchak** [comment]
> Why don't you just add your own element inside the perfect-scrollbar and catch the event from that?

Thanks, but unfortunately this doesn't work in case I want to catch the `mousedown` on the rail.

**Comment by sconix** [comment]
Well you can always use traditional JS ways so just addEventListener and use querySelector to find the rail. Afaik perfect-scrollbar does not send any events on rail clicks etc.
