### ISSUE TITLE
Missing module 

### ISSUE THREAD

**Issue by PyroFlaming** [zefoy/ngx-perfect-scrollbar#220]
After upgrade to angular 6 i have problem with the the 

```
ERROR in ./node_modules/ngx-perfect-scrollbar/dist/ngx-perfect-scrollbar.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/var/www/html/obf-v3/node_modules/ngx-perfect-scrollbar/dist'
```
import { Subject as Subject$1 } from 'rxjs/Subject';

**Comment by sconix** [comment]
That sounds like an issue with your node modules installation.

**Comment by PyroFlaming** [comment]
I remove and clear cache and install them again but same problem with the subject. 
is because in angular 6+ is the new rxjs 


  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "7.0.0",
    "@angular/common": "7.0.0",
    "@angular/compiler": "7.0.0",
    "@angular/core": "7.0.0",
    "@angular/forms": "7.0.0",
    "@angular/http": "7.0.0",
    "@angular/platform-browser": "7.0.0",
    "@angular/platform-browser-dynamic": "7.0.0",
    "@angular/router": "7.0.0",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "@types/moment": "^2.13.0",
    "@types/node-sass": "^3.10.32",
    "bootstrap": "^4.1.0",
    "braintree-web": "^3.37.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.5",
    "crypto-js": "^3.1.9-1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "moment": "^2.22.2",
    "ng2-file-upload": "^1.3.0",
    "ngx-cookie-service": "^1.0.10",
    "ngx-drag-scroll": "^2.0.2",
    "ngx-facebook": "^2.4.0",
    "ngx-perfect-scrollbar": "^5.3.5",
    "node-sass": "^4.9.2",
    "object-assign": "^4.1.1",
    "rxjs": "^6.3.3",
    "stacktrace-js": "^2.0.0",
    "tslint-angular": "^1.1.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "7.0.2",
    "@angular/compiler-cli": "7.0.0",
    "@compodoc/compodoc": "^1.1.5",
    "@types/googlemaps": "^3.30.15",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.106",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.3",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~2.0.0",
    "tslint": "~5.7.0",
    "typescript": "3.1.3"
  }

**Comment by sconix** [comment]
I already updated to Angular 7 and do not have this issue. So it must be something in your setup.

**Comment by PyroFlaming** [comment]
Yes i find the problem in the packages just. tnx for the help :)
