### ISSUE TITLE
Compatibility with angular 7

### ISSUE THREAD

**Issue by maku** [zefoy/ngx-perfect-scrollbar#221]
I tried to upgrad an existing app to angular 7. 

But the scrollbar (where I use the "perfect-scrollbar" component) looks ugly.

So my question: is ngx-perfect scrollbar compatible with angular 7?

TIA

**Comment by sconix** [comment]
I have no idea :) I will release 7.0.0 version during next week that will be tested and verified for Angular 7 compatibility. Afaik the current version should be compatible since there has been no API version increase in Angular 7.

**Comment by maku** [comment]
Great, thank you...

**Comment by sconix** [comment]
I just updated the libraries to Angular 7 and I do not see any style issues. So maybe you have some other updated library that causes style problems for the perfect-scrollbar?
