### ISSUE TITLE
iOS iphone crash on update-geometry

### ISSUE THREAD

**Issue by CorneThoes** [zefoy/ngx-perfect-scrollbar#222]
After using ngx-perfect-scrollbar for a couple of months now, we noticed a crash in our logs on iOS/iphone devices.

namely;
null is not an object (evaluating 't.scrollTop') at w.

after some investigation we found out that this is being called from the update-geometry.js method. 
The method is being called from applyTouchMove which in turn is being called from touchEnd.

After this i can see the stack going into the polyfill.ts, if additional info is needed let me know.

To reproduce this issue;
Route towards a page with perfect-scrollbar on an iphone device ( tested with iOS 11 and 10).
Swipe to go back to the previous page ( timing is important here, does not always happen ).
iOS 11 now freezes the browser ( safari )
iOS 10 keeps on throwing exceptions but does not freeze the browser ( safari )

If need be, I have a video of the issue, but it contains sensitive data so can not link it here.

Sincerely,

Corné

**Comment by sconix** [comment]
So this is most likely a bug in perfect-scrollbar since it coming from update-geoetry.js (or I guess this could also be in polyfill). I can also have a look when I have time, but maybe you could also report this in perfect-scrollbar repository issues since that's the most likely place where this issue is.

**Comment by CorneThoes** [comment]
Hey @sconix ,
also made an issue on the perfect-scrollbar repo:
https://github.com/utatti/perfect-scrollbar/issues/827

**Comment by CorneThoes** [comment]
It seems to be happening because of the fact that the container element is gone before the subscription ends. As in, the back event on iOS triggers before the event of perfect-scrollbar does.

I suspect the only reason polyfill is in there is because of the fact that is is iOS

**Comment by sconix** [comment]
That sound very plausible. Lets hope that perfect-scrollbar maintainer would soon come back to life. I have been waiting one bug PR to be merged and released for some time now.
