### ISSUE TITLE
Angular CDK Virtual Scroll

### ISSUE THREAD

**Issue by vahid-sohrabloo** [zefoy/ngx-perfect-scrollbar#223]
is there any example of how we can use perfect scrollbar with Angular CDK Virtual Scroll?

**Comment by sconix** [comment]
No, I would even say that it does not make sense to use PS with virtual scroll.

**Comment by vahid-sohrabloo** [comment]
why it does not make sense?

**Comment by vahid-sohrabloo** [comment]
this has the problem with Component but is work correctly whit PS directive.
thanks

**Comment by SanjanaMonga** [comment]
Hi @vahid-sohrabloo could you share the solution for using the PS directive with Angular CDK Virtual Scroll.
Thanks in advance.
