### ISSUE TITLE
No input were found in config file

### ISSUE THREAD

**Issue by amodolo** [zefoy/ngx-perfect-scrollbar#225]
Hi,
 i'm using this awesome library inside an Angular 7 project. Everything works like a charm but the TS linter give me this annoying message: 

> [ts] No input were found in config file 'node_modules/ngx-prefect-scrollbar/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were'["./dist"]'

Is it right that a compiled library has a tsconfig.json file inside?

Thanks for everything

**Comment by sconix** [comment]
Well there is no harm in having the file there although its not needed. Since your linter is complaining about that it means that its going through whole node_modules folder which is probably something you don't want it to do so I would look into setting up it correctly.

**Comment by sconix** [comment]
I removed the tsconfig.json file for upcoming release.
