### ISSUE TITLE
ps-scroll events are not emitted while the user is scrolling

### ISSUE THREAD

**Issue by ghost** [zefoy/ngx-perfect-scrollbar#234]
When I scroll my element by dragging it with a slow and constant movement, no ps-scroll-y event is emitted. It is only when I stop the movement, that ps-scroll-y is finally emitted.

This happen because the PerfectScrollbarDirective filters the browser scroll event with a debounceTime(20). this debounceTime prevents the ps-scroll-y event from being emitted until the browser stops sending scroll events.

Is this on purpose ? Is there a way to catch a scroll event without waiting for the user to end its movement ?
Maybe something like sampleTime() instead of debounceTime would be useful here ? It prevents the event from being emitted twice during a specific period, while still emitting it regularly.

**Comment by sconix** [comment]
I guess it should be throttleTime or sampleTime. I'll check and will release an update.

**Comment by sconix** [comment]
Hopefully 7.2.1 works more like you would expect it to, if not let me know :)

**Comment by cfoxy17** [comment]
Hi, I'm using "ngx-perfect-scrollbar": "^10.1.1" and was curious how to change this debounce / delay as the classes change from   ps ps--scrolling-y back to ps ps--active-y. I noticed my code that loads more rows as the user scrolls down cannot display the new rows until the class returns back to "ps ps--active-y".

**Comment by cfoxy17** [comment]
Update: i noticed if I use a normal scrollbar the update/load occurs almost instantly. **It seems there is a pretty significant delay in the time that the perfect scrollbar takes to visibly update the content once new content becomes available to be scrolled. I am only loading basic objects with ~10 key-value pairs in each row, and am attempting to concatenate only 20 more at a time.**

**Comment by cfoxy17** [comment]
Update again: I discovered if I only fetch 1 additional row instead of 20 at a time it takes the same amount of time to show the single new row. And I checked the API that fetches the data and it finishes almost instantly, while the ps content update is what's taking ~2 seconds to update. So it seems this issue occurs regardless of the size of data being concatenated.

**Comment by cfoxy17** [comment]
I also tried manually changing the class from "ps ps--scrolling-y" back to "ps ps--active-y" and sadly it's still taking too long to update :(

**Comment by cfoxy17** [comment]
Without ps:

![WithoutPerfscrollbar](https://user-images.githubusercontent.com/50955085/193627464-774dfd3e-98a8-4887-a50e-5382d7b06603.gif)

With ps:

![WithPerfscrollbar](https://user-images.githubusercontent.com/50955085/193627513-952b0c2a-0e39-4cb4-98b1-25c462389e25.gif)
