### ISSUE TITLE
Feature Request. Scroll Horizontally to a specific position

### ISSUE THREAD

**Issue by gnasit** [zefoy/ngx-perfect-scrollbar#24]
Could you please add a method similar to the scrollTo(position) in the directive and the component. Something along the lines of the below, this way we can scroll to specific position programmatically as well..

for the directive ->
`PerfectScrollbarDirective.prototype.scrollToLeft = function (position) {
        this.elementRef.nativeElement.scrollLeft = position;
        this.update();
    };`

for the component ->
`PerfectScrollbarComponent.prototype.scrollToLeft = function (position) {
        this.elementRef.nativeElement.scrollLeft = position;
        this.update();
    };`

**Comment by sconix** [comment]
Sure I can add optional x,y format for the scrollTo and and short hand functions for scrolling to most left / right.

**Comment by sconix** [comment]
I just released 2.0.5 which has the scrollTo(y) and scrollTo(x, y) possibility with scrollToTop/Left/Right/Bottom(offset) helper functions.
