### ISSUE TITLE
Scrolling over an iframe

### ISSUE THREAD

**Issue by vinayakpatil** [zefoy/ngx-perfect-scrollbar#245]
Scrolling over an iframe via mouse wheel does not work/

Can we capture mouse-wheel event from iframe as mentioned in below issue?
Reference: https://github.com/utatti/perfect-scrollbar/issues/327

**Comment by sconix** [comment]
You are asking in the wrong place, I am not an PS expert since this is just a simple Angular wrapper nothing else. I leave this open if somebody else knows something.

**Comment by vinayakpatil** [comment]
Hi @sconix , I don't think this is the wrong place. Since this is a wrapper of ps, we can try to add workaround suggested in https://github.com/utatti/perfect-scrollbar/issues/327 on iframes.

I can give it a try and raise a PR if you are okay.

**Comment by sconix** [comment]
In that case yes this is not wrong place. To me that workaround seems bit hacky, especially since if I understand it correctly it is then applied to also for browsers that do not have any issues.

If the PR is reasonable and it only fixes the issue when it needs fixing i.e. does not add any overhead for browsers that do not need it then I will gladly merge it. But if its hacky in a way that its not properly "isolated" then I would think that the fix should be made in the applications when / if needed and not included in a generic library like this.

**Comment by beyondtheobservableuniverse** [comment]
Any solution for this bug?

**Comment by TopDuke** [comment]
Any solution for this bug?

**Comment by vinayakpatil** [comment]
Just fixed this by writing a simple util shared below.

Usage: `EventUtils.bubbleFrameMouseWheel(iframe, 'div.ps');`

```
public static bubbleFrameMouseWheel(frame: HTMLIFrameElement, targetSelector: string): void {
    const onwheel = (event: any): void => {
      const newEvent: any = document.createEvent('MouseEvents');
      let newTarget: Window | Element = parent;

      newEvent.initEvent('wheel', true, true);
      newEvent.deltaMode = event.deltaMode;
      newEvent.deltaX = event.deltaX;
      newEvent.deltaY = event.deltaY;
      newEvent.deltaZ = event.deltaZ;
      newEvent.wheelDelta = event.wheelDelta;
      newEvent.wheelDeltaX = event.wheelDeltaX;
      newEvent.wheelDeltaY = event.wheelDeltaY;

      try {
        if (isString(targetSelector)) {
          newTarget = frame.closest(targetSelector) || parent;
        }

        newTarget.dispatchEvent(newEvent);
      } catch (e) {
        console.error('Failed to dispatch iframe wheel event');
      }
    };

    const frameWindow = frame.contentWindow;
    if (!isUndefined(frameWindow.onwheel)) {
      frameWindow.onwheel = onwheel;
    } else if (!isUndefined(frameWindow.onmousewheel)) {
      frameWindow.onmousewheel = onwheel;
    }
  }
```
