### ISSUE TITLE
PS disables smooth scrolling

### ISSUE THREAD

**Issue by IamTC** [zefoy/ngx-perfect-scrollbar#257]
Scrolling feels twitchy. The native smooth scrolling from the browser is lost with the plugin. Tested in Chrome and firefox latest versions. This is visible in the stackblitz example in the read me as well.

Any help will be appreciated. Thanks.

**Comment by sconix** [comment]
You only get smooth scrolling with native scrolling.

**Comment by IamTC** [comment]
@sconix Thanks for clarifying.
