### ISSUE TITLE
[bug] scroll is not working with ngx-ckeditor

### ISSUE THREAD

**Issue by indraraj26** [zefoy/ngx-perfect-scrollbar#264]
When you mouseenter over ckeditor then you wont be able scroll with mouseWheel. but when you mouseover then you will able to scroll.

Reproduce: I think it is because of iframe as ngx ckeditor uses iframe

**Comment by sconix** [comment]
I am pretty sure there is nothing I can do for this. This sounds like an limitation of perfect-scrollbar.
