### ISSUE TITLE
Blend out scrollbar if unused

### ISSUE THREAD

**Issue by JMD49591** [zefoy/ngx-perfect-scrollbar#270]
Hi,
I'm using your library inside a menu and for that purpose I find it kinda annoying if it stays there all the time. Could you add an option that provides hiding the scrollbar if not hovering above it and not scrolling? So that it only appears if you want to scroll?

**Comment by sconix** [comment]
You can easily do it with CSS so there won't be such option in the code.

**Comment by JMD49591** [comment]
@sconix thanks for your reply. I did just that.
For looking forward to other people might wanting the same solution, it could be a better to just provide such options in the future.

Anyways for other people that want a same solution, this is what I did:
```CSS
.ps:hover:not(.ps--scrolling-y) > .ps__rail-y:not(:hover) {
  opacity: 0;
}
```
It's the same behaviour like on [Twitch](https://www.twitch.tv/).
