### ISSUE TITLE
Custom event emitted by psScrollY does not contain "ctrlKey", "shiftKey" info

### ISSUE THREAD

**Issue by Zordaxy** [zefoy/ngx-perfect-scrollbar#273]
Custom event emitted by psScrollY and possibly all other emitters does not contain "ctrlKey", "shiftKey" info. There is no way to know if such buttons were pressed.
![Screenshot_211](https://user-images.githubusercontent.com/28386943/73011721-cf6aaf00-3de2-11ea-8afc-dd8a992cebcc.png)

**Comment by sconix** [comment]
This is a issue for perfect scrollbar not for this library.
