### ISSUE TITLE
Can't resolve 'resize-observer-polyfill'

### ISSUE THREAD

**Issue by xidedix** [zefoy/ngx-perfect-scrollbar#274]
Versions (fresh install):
- ngx-perfect-scrollbar `9.0.0-3`
- angular `9.0.0-rc.10`

I am getting an error:
```
ERROR in ./node_modules/ngx-perfect-scrollbar/fesm5/ngx-perfect-scrollbar.js
Module not found: Error: Can't resolve 'resize-observer-polyfill' in './node_modules/ngx-perfect-scrollbar/fesm5'
```
Workaround: 
`npm i resize-observer-polyfill`

Can anyone confirm the issue?

**Comment by sconix** [comment]
It seems that was missing from the library dependencies. Is fixed in the 9.0.0 release.
