### ISSUE TITLE
When will the 9.x.x version be released?

### ISSUE THREAD

**Issue by heecheolman** [zefoy/ngx-perfect-scrollbar#275]
[Window surface issue was merged](https://github.com/zefoy/ngx-perfect-scrollbar/pull/272). So I'm waiting for 9.x.x. version this week.
When will the 9.x.x version be released?

**Comment by ghost** [comment]
Would be happy about this, too :)

**Comment by sconix** [comment]
There has been 9.x.x pre-release for a while now. 9.0.0 will be out now.
