### ISSUE TITLE
Problem with the directive styling

### ISSUE THREAD

**Issue by HoplaGeiss** [zefoy/ngx-perfect-scrollbar#276]
I noticed a problem with the directive's styling.
When importing the directive in scss like so `@import '~perfect-scrollbar/css/perfect-scrollbar.css'`, the scrollbar behavior works, but the scrollbar is invisible at all time.
But when importing the style through `<link rel="stylesheet" href="https://unpkg.com/perfect-scrollbar/css/perfect-scrollbar.css" />` then it works fine.

**Comment by sconix** [comment]
I do not think this is related to this library. I would say it depends on your build setup what works and how.
