### ISSUE TITLE
Reaching the end of scrollable content, scrolls the page too without moving the mouse

### ISSUE THREAD

**Issue by PedroCNunes** [zefoy/ngx-perfect-scrollbar#278]
Hi! 
When I'm scrolling (with the mouse wheel) on a scrollable div and it reaches the end and I continue to roll the mouse wheel (without moving the cursor) the main page starts scrolling. Now, this shouldn't happen until I move the cursor. That's the default way. 

I don't know if I'm missing some property or this is a bug or even a feature that was not implemented.

![scroll-bug](https://user-images.githubusercontent.com/17788348/74046438-7b58f080-49c6-11ea-8122-66542293375e.gif)

Hope you can help me.

**Comment by sconix** [comment]
I have never heard of such default behavior nor bumped into one ever (of course it can be some OS/browsers default way with native scrolling). Anyway PS does not offer any controls for propagation other than turning it off. This library offers an extra autoPropagation option which can be used to get a behavior where one needs to do small pause in the scrolling before events are propagated to the parent. You can always implement your own behavior, but as said PS does not offer any propagation "modes".

**Comment by PedroCNunes** [comment]
Thanks for your response. Actually what I needed was the autoPropagation to true. Now works fine.

Thanks :)
