### ISSUE TITLE
Change the Scroll Top position of perfect scroll in angular 2

### ISSUE THREAD

**Issue by chandrakailash1993** [zefoy/ngx-perfect-scrollbar#29]
Hi

I want to update the scroll position from top when i show hide a component/div in angular 2.

I tried to this way, which did not worked.

@ViewChild('messagesContainer') messagesContainer: ElementRef;
this.messagesContainer.elementRef.nativeElement.scrollTop = 170;

Is there any update for this.

Regards

Kailash

**Comment by sconix** [comment]
Both the perfect scrollbar directive and component has scrollTo(position) / scrollToTop(offset) / scrollToBottom(offset) methods.

**Comment by AKHACHKHOUCH** [comment]
is it valide in angular 10 ?
