### ISSUE TITLE
Angular 10 support 

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [zefoy/ngx-perfect-scrollbar#290]
Please upgrade project to Angular 10

![image](https://user-images.githubusercontent.com/30147726/87141932-13277700-c2a4-11ea-99a2-7b410d941f67.png)

**Comment by sconix** [comment]
Will do as soon as I have time. I am in middle of finishing building of my house and moving in so pretty busy atm. At the latest will have time next month, but will do update this asap when I just have little bit of time.
