### ISSUE TITLE
in angular 10 it does not build correctly

### ISSUE THREAD

**Issue by koraysels** [zefoy/ngx-perfect-scrollbar#294]
I get a warning followed by an Error. 
fresh angular project with 
```
    "@angular/common": "~10.0.14",
    "@angular/core": "~10.0.14",
```

installed.

this is the console output: 

```
WARNING in Entry point 'ngx-perfect-scrollbar' contains deep imports into '/Users/koraysels/work/__UNDEFINED__/projects/kvs-247.be/web/app/themes/kvs/node_modules/rxjs/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "ngx-perfect-scrollbar" has missing dependencies:
 - @angular/core
 - @angular/common
```

**Comment by navap1polak** [comment]
I have the same issue.
Where you able to solve the issue?

**Comment by koraysels** [comment]
> I have the same issue.
> 
> Where you able to solve the issue?

In my case I had it intalled in the wrong package.json in the wrong directory.

**Comment by navap1polak** [comment]
I'm completely new to angular.
I have installed angular v 10.6
Any specific actions to make? reinstall angular?

Thanks, Nava.

**Comment by koraysels** [comment]
Just use ng cli to init a new project and the do the npm install ngx-perfectscroll . After that it will work;)
