### ISSUE TITLE
Disable PS on mobile/tablets

### ISSUE THREAD

**Issue by Flood** [zefoy/ngx-perfect-scrollbar#30]
Hi!

Is it possible to disable Perfect Scroll on mobile devices? Can't get it to work properly on Iphone/Ipad (Android works) so I want to use the native scroll instead.

I am using the directive like this

```
<div [perfect-scrollbar]>
      //Stuff
</div> 
```

I don't want two div tags btw, so I need a way to disable it on mobile devices.

**Comment by sconix** [comment]
I haven't noticed any problems on iOS devices. We are nearing a release of our project which uses this library and is required to work on wide range of mobile devices, if we find any problems during the final testing period I will add tweaks / fixes etc.

Are you sure that your styles or the div structure is not causing the problem? We are using the component atm and at least with that I haven't noticed any problems.

**Comment by Flood** [comment]
@sconix: I've tried the component instead.
```
HTML
<perfect-scrollbar class="col-xs-12 col-sm-9 col-md-8 col-lg-8 site-content-container">
	//stuff		
</perfect-scrollbar>
```

```
CSS
.site-content-container {
  max-height: 100vh;
  overflow-y: auto;
  display: inline-block;

  @include media-breakpoint-down(sm) {
    max-height: calc(100vh - 48px);
  }
}
```

I need a max-height in order for the scroll to show up. Do you have a max-height, height or min-height on your component?

**Comment by sconix** [comment]
I don't think we are using max-height anywhere, we rely on flex layout and are using flex-layout library.

**Comment by sconix** [comment]
In the previous release I added disabled property so that one can disable the PS functionality. So you should be able to use that on mobile if you want to have the native scrolling.

**Comment by maikldan** [comment]
sorry but disable function doesn't work(

**Comment by sconix** [comment]
Disable just unloads perfect-scrollbar so it works. When disabled you can style the classes so that you get normal scrollable area.

**Comment by maikldan** [comment]
Hi, i tried to make scroll bar as a directive, with ps style but scroll bar
doesn't work. I add Import statement like in docs but nothings change

**Comment by sconix** [comment]
Not sure what do you mean. Are you still talking about disable true option? If yes then what I am trying to say that when disabled this lib basically does nothing i.e. you need to make the scrolling area yourself with styles etc.
