### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by johanvdb** [zefoy/ngx-perfect-scrollbar#31]
On a mobile device (Samsung Galaxy S7), I can touch scroll once, thereafter an exception is thrown which prevents further scrolling:

```
Uncaught TypeError: Cannot read property 'length' of null
    at Zone.webpackJsonp.1724.Zone._updateTaskCount (zone.js:224)
    at Zone.webpackJsonp.1724.Zone.cancelTask (zone.js:214)
    at zone.js:1575
    at clearInterval (eval at createNamedFn (zone.js:1483), <anonymous>:3:40)
    at HTMLElement.touchStart (touch.js:84)
    at ZoneDelegate.webpackJsonp.1724.ZoneDelegate.invokeTask (zone.js:363)
    at Zone.webpackJsonp.1724.Zone.runTask (zone.js:166)
    at HTMLElement.ZoneTask.invoke (zone.js:416)
webpackJsonp.1724.Zone._updateTaskCount @ zone.js:224
webpackJsonp.1724.Zone.cancelTask @ zone.js:214
(anonymous) @ zone.js:1575
clearInterval @ VM5339:3
touchStart @ touch.js:84
webpackJsonp.1724.ZoneDelegate.invokeTask @ zone.js:363
webpackJsonp.1724.Zone.runTask @ zone.js:166
ZoneTask.invoke @ zone.js:416
```

Using 
ngx-perfect-scrollbar 2.5.0
perfect-scrollbar 0.6.16

I have no customizations to the default config, and just use the "perfect-scrollbar" directive with content too big for the screen. 

As a test, if I comment out the easing loop interval created on line 125 of touch.js, the errors go away and scrolling works fine without easing.

**Comment by sconix** [comment]
I try to check this during this week and make a bug fix release if there is something to be fixed in this library. If you can make or have a Plunker example that I can use to verify this it would help or does the error happen also with the example app which link is in the readme?

**Comment by johanvdb** [comment]
Mmm, so I created a plunker and in there the issue does not seem to happen: https://embed.plnkr.co/edXAWpQHQ2j6GIIVSQKd/

The issue only seems to occur when I use the theme below:
https://themeforest.net/item/fury-angular-2-material-design-admin-template/19325966

I have logged a support ticket with them.
