### ISSUE TITLE
Any plans on Angular 4 support?

### ISSUE THREAD

**Issue by madebysoren** [zefoy/ngx-perfect-scrollbar#32]
Any plans on Angular 4 support?

**Comment by madebysoren** [comment]
And then I saw you are already on it :)

**Comment by sconix** [comment]
Yes there is already 4.x versions released that fully support Angular 4. The old 2.x versions might also work but I like to keep the major version in sync with Angular version so that its clear that when major Angular version is tested / fully supported.
