### ISSUE TITLE
config handlers not working in ie edge

### ISSUE THREAD

**Issue by jiann4321** [zefoy/ngx-perfect-scrollbar#34]
<perfect-scrollbar [config]="{handlers: ['click-rail', 'drag-scrollbar', 'wheel', 'touch']}" class="pipeline-workspace" rpNodeDroppable>

I can still use the keyboard keys in IE edge v14. Chrome works fine :(

**Comment by sconix** [comment]
I guess you should report this in the perfect-scrollbar project. At least I don't think this is due to Angular, but could be wrong.
