### ISSUE TITLE
Feature Request: Add Use as Polyfill Support

### ISSUE THREAD

**Issue by sabbirrahman** [zefoy/ngx-perfect-scrollbar#35]
It will be great if there is a way to use ngx-perfect-scrollbar as a polyfill for browser that doesn't support custom scrollbar. May be add a polyfill property in the config object? Or you can let us(developers) do the browser support checking task and pass a boolean property to disable the scrollbar for supported browsers?

**Comment by sconix** [comment]
I'll check adding of disabled property next week once I am back from my holiday.

**Comment by sconix** [comment]
Sorry that I forgot this issue, but now there is disabled flag in 4.3.0 which allows disabling ps functionality, hopefully this is what you wanted.
