### ISSUE TITLE
Is possible to use this directive on <body> tag?

### ISSUE THREAD

**Issue by alienriquebm** [zefoy/ngx-perfect-scrollbar#37]
My project render my components on this structure:

```
<body>
     <main-app>Loading...<main-app>
.
.
.
</body>
```
I able to apply the scrollbars into any component of <main-app>.
Is any way to apply the scrollbars to the body tag? Thanks!

**Comment by sconix** [comment]
Why do you need them in body tag?

**Comment by sconix** [comment]
I don't see any reason for placing it into body. Just put it in the top most div of your app. I don't think Angular can place directives to components outside of the application, but for that you need to refer Angular documentation.
