### ISSUE TITLE
Cant use directive in a sub component 

### ISSUE THREAD

**Issue by drisschelouati** [zefoy/ngx-perfect-scrollbar#39]
##Thte title says it all. In my app, i have the perfect scrollbar module imported and declared in my **layout.module.ts** :
 
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';
import { MaterialModule } from '@angular/material';

import { LayoutRoutingModule } from './layout-routing.module';
import { LayoutComponent } from './layout.component';
import { HeaderComponent, SidebarComponent, SidenavComponent, HamburgerComponent, } from '../shared';
import { PerfectScrollbarModule } from 'ngx-perfect-scrollbar';
import { PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';

const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};

@NgModule({
    imports: [
        CommonModule,
        NgbDropdownModule.forRoot(),
        MaterialModule,
        PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG),
        LayoutRoutingModule,
    ],
    declarations: [
        LayoutComponent,
        HeaderComponent,
        SidebarComponent,
        SidenavComponent,
        HamburgerComponent,
    ]
})
export class LayoutModule { }

```

it works perfectly when i call it from **layout.component.ts**. However when i try using the directive in a child component, let's say **user-profile.ts**, an error tells me that [perfect-scrollbar] is not a known element. If i try importing the PS module again in my submodule or subcomponent, i also get errors. Iam probably doing something wrong, anyone could help me figure it out ?

**Comment by sconix** [comment]
You need to import the module in all of the submodules where you use it. When using in submodule then you just import PerfectScrollbarModule without the forRoot part.

**Comment by drisschelouati** [comment]
perfect answer ! that worked nicely. Thanks for your support.
