### ISSUE TITLE
can not make it work with latest angular 2 project built with angular cli

### ISSUE THREAD

**Issue by axcl** [zefoy/ngx-perfect-scrollbar#4]
can not make it work with latest angular 2 project built with angular cli

**Comment by sconix** [comment]
We are using this all the time in project build with angular-cli and we try to keep our project up to date with all the angular-cli changes, but I can try with newly generated project.

**Comment by sconix** [comment]
At least it works for me in new project created with angular-cli beta18 + angular 2.1.2. Make sure you have a fixed height with the scrollbar area (by using flex or static height etc.) otherwise you don't get scrollable area.

**Comment by sconix** [comment]
I am closing this for now, if you are sure there is a problem with the library and can provide me an example code then I can re-open this.
