### ISSUE TITLE
Upgrade to  Angular 4?

### ISSUE THREAD

**Issue by ghost** [zefoy/ngx-perfect-scrollbar#40]
Any plans to update the peerdependencies to Angular 4?

I get build / compile errors when using your library with Angular 4.

**Comment by sconix** [comment]
Peer dependencies are >=2.0.0 so using 4 should perfectly fine. I don't get any build / compile errors with Angular 4.

**Comment by josephserrano15** [comment]
I don't get any error either, but here how my HTML look like.(cannot see the scroll bar). Maybe I am doing something wrong. I copy the test solution into mine to test, without success.

`<div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div>`

**Comment by sconix** [comment]
You most likely have issues with your styles nothing to do with Angular version.

**Comment by josephserrano15** [comment]
Do you have the native styles, so I can directly apply them?

**Comment by josephserrano15** [comment]
Never mind I got it.

**Comment by ghost** [comment]
Oh sorry... In all the rush I ran "yarn add" in wrong folder...

Forget it, my mistake :)
