### ISSUE TITLE
Add minimal example without angular flex

### ISSUE THREAD

**Issue by Celebes** [zefoy/ngx-perfect-scrollbar#42]
Just plain simple html with css, please. I am trying to make this work in my project for 15 minutes now and I shouldn't.

**Comment by sconix** [comment]
Well the example is already as minimal as it can and it is plain and simple html / CSS. All that angular flex does is sets the flexbox styles and if you know CSS then you know that all that flexbox styles do is set width and height for the elements. So without angular flex you just define width / height with other CSS styles. There would not be any other difference with the example app. Like with all scroll areas, the scroll area needs size set or they just expand and scroll will never appear.
