### ISSUE TITLE
How to update ngx-perfect-scrollbar?

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#43]
The content that is in <perfect-scrollbar></perfect-scrollbar> has changed, I want to update the perfect-scrollbar, how to do?

**Comment by xuwenqing2014** [comment]
I known how to update , but the code @ViewChild(PerfectScrollbarDirective) directiveScroll; why directiveScroll is 'undifined'?

**Comment by sconix** [comment]
Are you trying to access it before view is initialized? Anyway the ViewChild usage is not library specific so you might find help easier just by googling ViewChild usage.

**Comment by kotmatpockuh** [comment]
any update?

**Comment by xuwenqing2014** [comment]
Beacuse if the 'perfect-scrollbar' directive is not exist in html, 'directiveScroll' might be 'undifined', sorry
