### ISSUE TITLE
Why scrollbar is also exist?

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#46]
when the content that is in 'perfect-scrollbar' is just one column,  but scrollbar is also exist? Can not hidden scrollbar in that case?  the ngx-perfect-scrollbar demo is also like that.

**Comment by sconix** [comment]
There seems to be small bug in the component default styles, the directive does work correctly. I will release a new version where the min-height of ps-content is removed which causes the scrollbar to appear.

This should be fixed in 4.2.0.
