### ISSUE TITLE
The scrollbar is disappeared

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#47]
When I dragging the scrollbar , if mouse pointer is moved outside 'perfect-scrollbar', the scrollbar is disappeared

**Comment by sconix** [comment]
At least I can't reproduce that in the example. Maybe you have some element "stealing" the mouse events or some other problem with styles etc. But if you mean that the other scrollbar disappears (not the one you are dragging) then its how its supposed to be and that you can change yourself by overriding the default styles.

**Comment by xuwenqing2014** [comment]
I mean that the 'perfect-scrollbar' scrollbar disappears. It has not occur in the example, but in my project is occur, so it is very strange, I have not solve this issue so far, thanks.

**Comment by sconix** [comment]
If you can make some example where the problem exists I can check it out, but without way to reproduce I would say its some styling issue or some other component is stealing the mouse events.
