### ISSUE TITLE
Whether there is some events like 'ps-y-reach-end' or 'ps-y-reach-start'?

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#49]

**Comment by xuwenqing2014** [comment]
I need to implement this functionality that loading data when scroll to top

**Comment by sconix** [comment]
Yes you can listen to all perfect scrollbar events just add wanted output handling for the event i.e. (ps-y-reach-end)="function($event)"

**Comment by xuwenqing2014** [comment]
Thanks, It is cool.
