### ISSUE TITLE
Unexpected value 'PerfectScrollbarModule' imported by the module '<ModuleName>'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by heyanctil** [zefoy/ngx-perfect-scrollbar#51]
I try to import the PerfectScrollbarModule in a Module (MainToolbarModule) where we use it in a component who is part of library. That scenario seems to work fine, I have a small project in that library where I can execute and load the perfect-scrollbar.

But when I try to use that library in another project (as a dependency!), I get : «Unexpected value 'PerfectScrollbarModule' imported by the module 'MainToolbarModule'. Please add a @NgModule annotation.»

Have you ever encountered this scenario?

The module where I import PerfectScrollbarModule looks like this (MainToolbarModule is exported and his other components work fine with the application):
```
...
import {PerfectScrollbarModule} from "ngx-perfect-scrollbar";
...

@NgModule({
    imports: [
        ...
        PerfectScrollbarModule
    ],
    schemas: [NO_ERRORS_SCHEMA],
    declarations: [
        ...
    ],
    entryComponents: [
        ...
    ],
    providers: [
        ...
    ],
    exports: [
        ...
    ],
})
export class MainToolbarModule {
}

```

**Comment by sconix** [comment]
I am not sure I follow you, but to me that sounds like the perfect scrollbar library isn't installed or it can't be found by your project. Haven't encountered such situation, but it has to be something to do with your configuration / setup most likely.

**Comment by vugar005** [comment]
Had exact issue before. Issue solved thanks to sconix. The problem probably because you import module from ngx-perfect-scrollbar/dist
instead of ngx-perfect-scrollbar.
