### ISSUE TITLE
Update container state after window resize (ChangeDetectionStrategy.OnPush)

### ISSUE THREAD

**Issue by al-pt-old** [zefoy/ngx-perfect-scrollbar#54]
Hi there!

There is an issue when the window is being resized.

https://github.com/zefoy/ngx-perfect-scrollbar/pull/53

**Comment by sconix** [comment]
Ok, normally there should not be, the doCheck should notice all size changes no matter if its window resize or not. 

There can be problem if using onPush or manual change detection so I think your PR to add the call for window resize is not a bad addition. I will include this in the upcoming 4.5.0 release.

**Comment by sconix** [comment]
The next 4.5.0 brings couple new features and code re-factoring so that component now uses the directive. I will modify your PR to suite the new code structure.

**Comment by al-pt-old** [comment]
Thanks

**Comment by al-pt-old** [comment]
FYI

This workaround works for me

```
@Component({
  ...
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class MyComponent implements AfterContentInit, AfterViewInit, DoCheck {

  @ViewChild('ps') ps: PerfectScrollbarComponent;

  ngDoCheck(): void {
    this.ps.ngDoCheck();
  ...
  }
```
