### ISSUE TITLE
Angular 4 compatiblity

### ISSUE THREAD

**Issue by PyRowMan** [zefoy/ngx-perfect-scrollbar#55]
Hey guys I've seen that you were using angular 4.0.0 as dependencies.

So I wanted to use your librairy into my angular 4 project, but when i tried to install it, i got an unmet peer dependency on angular2.0.

Is it normal ? 

Here are the log : 

```
npm update
audio-viz@2.0.0 C:\www\audioViz
+-- UNMET PEER DEPENDENCY @angular/common@4.2.5
+-- UNMET PEER DEPENDENCY @angular/core@4.2.5
+-- UNMET PEER DEPENDENCY @angular/platform-browser@4.2.5
+-- ngx-perfect-scrollbar@4.4.0
-- UNMET PEER DEPENDENCY zone.js@0.8.12

npm WARN angular2-perfect-scrollbar@2.0.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-perfect-scrollbar@2.0.6 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-perfect-scrollbar@2.0.6 requires a peer of @angular/platform-browser@^2.0.0 but none was installed.
npm WARN angular2-perfect-scrollbar@2.0.6 requires a peer of zone.js@^0.7.0 but none was installed. 
```

**Comment by sconix** [comment]
No it is not normal, I use the library without problems in Angular 4 project. The peer dependency is with >= 2.0.0 so any version above 2 is ok.

**Comment by sconix** [comment]
But why are you installing 2.0.6 version of the library? That might have dependency to 2.x. The latest version is 4.4.0.
