### ISSUE TITLE
The version 4.5.0

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#56]
The version 4.5.0 has not come out in npm , it has't offer the function that can get the scrollbar's scrollHeight. Could you solve it？

**Comment by sconix** [comment]
Yes I am still in process of verifying that everything works, I will release it in npm today or at the latest tomorrow. And I will still make a small change to have helper function for height / width. 

I accidentally pushed the version to git already, but will override it once the release is ready for npm.
