### ISSUE TITLE
After doing an AOT build, I get "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by Sebastian23** [zefoy/ngx-perfect-scrollbar#57]
I'm using Angular 4 and the AOT bundle was obtained using Rollup. The error is around the line: 
module.exports=require("./src/js/main");

**Comment by sconix** [comment]
I am not familiar with Rollup so can't help you with your build setup. Hopefully somebody knows what the problem is but afaik the problem should not be in this library.

**Comment by sconix** [comment]
The example app has SystemJS and Webpack (AOT + JIT) versions and I will gladly add some other build system examples if somebody makes a PR.
