### ISSUE TITLE
Doesn't work in FF 49.0.2

### ISSUE THREAD

**Issue by fpmk** [zefoy/ngx-perfect-scrollbar#6]
Seems this doesn't work in FF for me
There is no errors or something.  (All perfect in Chrome)
![1](https://cloud.githubusercontent.com/assets/1199499/20298616/6e91942a-ab49-11e6-870b-c1ef853ef364.jpg)

**Comment by sconix** [comment]
Looks likes Firefox styling issue, I am pretty sure that the example app is missing the proper flexbox styles needed for Firefox. At least I am 99% sure that there is nothing wrong with the library, but will make sure and fix the example for next update.

**Comment by sconix** [comment]
I was right the Firefox is acting weird when it comes to flexboxes, it sometimes wants the min-height 0 in the styles for it to work properly. So I updated the example app to work on Firefox as well.

**Comment by fpmk** [comment]
Thanks! It works now.
