### ISSUE TITLE
Cleanup / improve the component styles

### ISSUE THREAD

**Issue by sconix** [zefoy/ngx-perfect-scrollbar#62]
- Remove old ps-spacing-* helper classes.
- Tweak the default styles to look pretty in all situations.
- Add documentation about the flex attributes and their effect on styles

**Comment by diagramatics** [comment]
I'd like to raise a concern on https://github.com/zefoy/ngx-perfect-scrollbar/blob/7f477de3215a2dea07739481daec3830fe5e2dc0/src/lib/perfect-scrollbar.component.scss#L12 just so it gets noticed. This does mean that if we don't use `flex-layout` there's a chance that using this module on a flex item or child will result in a broken look right?

**Comment by sconix** [comment]
Not sure I understand the question fully. If you are not using flex-layout I don't think that your component will have fxflex attribute set. At least I am not aware of any other library that would use similar attributes. At least I have tried to set the styles so that they only have an effect if you use flex-layout library and apply those directives for the perfect-scrollbar component.
