### ISSUE TITLE
Nested Scrollbars will update indicators on parent scrollbars

### ISSUE THREAD

**Issue by Argannor** [zefoy/ngx-perfect-scrollbar#66]
When nesting Angular components which each use this scrollbar you can observe, that the scrolling indicators will update when scrolling inside a child. This is caused by the upwards propagation of the scroll event through the DOM.

Imagine a page with some scrollable content, which in turn has a drop down select with a scrollbar for it's menu. Now scroll to the bottom inside the drop down menu which will set the class .at-bottom for div.ps-overlay on both the dropdown's scrollbar and the main page's scrollbar.

I'll include a PR that fixes the problem by checking the event's current target agains the event's target. However this might need some additional testing...

**Comment by sconix** [comment]
Nice catch and thanks for the PR, will merge tomorrow and release new version after verifying that it wont cause any problems. At least it looks ok to me.

**Comment by sconix** [comment]
I can't see any problems with the fix so I released a new version.

**Comment by Argannor** [comment]
Thanks for the quick release!
