### ISSUE TITLE
perfect-scrollbar.component.css throws error in AoT mode

### ISSUE THREAD

**Issue by roysudi** [zefoy/ngx-perfect-scrollbar#69]
Hello!

Noticed an issue while converting our app from JIT to AOT. It seems the perfect-scrollbar component is using scss code inside a css file that irks the webpack loaders in AoT mode. I have couple of my own packages pushed inside node_modules & hence can't do a simple "node_modules" exclude. 

I believe the file should be converted to scss if using inheritance etc. else replace it with plain css.

Thoughts?

Regards,
Suds

**Comment by roysudi** [comment]
my bad, it was vscode fooling me by indenting the file that made it look like using inheritance. So It is actually a valid css file. 

However, I am not sure why I keep getting the below error:
Error processing file: ..../node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css

Followed by:
ERROR in <css input>:1:10: Unknown word

This error goes away on excluding ngx-ps

Thoughts on this please

**Comment by sconix** [comment]
I remember seeing that sort of error with some library, only if I could remember the reason. What build system are you using?

**Comment by roysudi** [comment]
Angular 4/Webpack 3. Any clues would be helpful, have been struggling since morn.

**Comment by sconix** [comment]
Is it a custom setup or angular-cli? If custom then could the example app aot configuration provide help. If angular-cli then I have no ides since it works in our angular-cli project.

**Comment by sconix** [comment]
I really have no idea, it some how sounds like an issue with the webpack css / style loaders configuration.

**Comment by roysudi** [comment]
It's a custom setup, will take another look at your example setup. Thanks for your help

**Comment by sconix** [comment]
Your welcome, sorry that I can't be more help. I am not that familiar with the webpack that could pinpoint the reason. In our primary project we use angular-cli so there has been no need to dig into webpack more closely.

**Comment by roysudi** [comment]
Not an issue, I'll close this issue for now, hopefully it's something to do with the loaders. Thanks!
