### ISSUE TITLE
 How to make a scrollto?

### ISSUE THREAD

**Issue by GitHubish** [zefoy/ngx-perfect-scrollbar#7]
Hello,

I'm trying to scrollto an item in the scrollbar container but it does not work. I tried with different other modules like:
- [ng2-scrollable](https://github.com/ng2-ui/ng2-scrollable)
- [ng2-page-scroll](https://github.com/Nolanus/ng2-page-scroll)

With the original perfect-scrollbar it seems to be possible.

Can you help me. Thank you

**Comment by sconix** [comment]
At the moment we are doing that like this: document.getElementById('workflow-card').scrollIntoView(); Naturally you could use elementRef to get the nativeElement, but point being is that the standard way of calling scrollIntoView for an elements works.

I have also planned to look into more Angular 2 way of doing that, but haven't had time yet. When I do if I find a better way and it can be handled by the library I will add some direct support, but for now the scrollIntoView works nicely.
