### ISSUE TITLE
Scrollbar doesn't work in flex-box without angular/flex-layout fxFlex attribute

### ISSUE THREAD

**Issue by 808brinks** [zefoy/ngx-perfect-scrollbar#76]
I have a flex-box layout with a scrollbar in it but it only works when i add the 'fxFlex' attribute to the <perfect-scrollbar> element.

Seems that this adds some css to the perfect-scrollbar (perfect-scrollbar.component.scss:12).

It would be nice if i didn't need add this attribute but could just have a @input() or a css class I can add to make this scrollbar work.

I don't use angular/flex-layout because it's still in beta.

Examples:
Not working:
```
<div class="d-flex flex-column h-100">
    <div class="d-flex flex-column" style="flex: 1 1 auto; min-height: 0; position: relative;">
        <perfect-scrollbar>
              .. some long content
        </perfect-scrollbar>
    </div>
</div>
```

Working:
```
<div class="d-flex flex-column h-100">
    <div class="d-flex flex-column" style="flex: 1 1 auto; min-height: 0; position: relative;">
        <perfect-scrollbar fxFlex>
              .. some long content
        </perfect-scrollbar>
    </div>
</div>
```

**Comment by sconix** [comment]
It would be waste of resources to try determine the flex box from the styles and having separate inputs would not bring anything new to the table imho. At least to me it does not make that much difference is it attribute or class or input.

So I think the best would be just to document the attributes / flex-layout usage, but have been bit busy for adding such things to the README. If there is some sort of standard for flex input parameters or you have seen such things in other libraries I am not agains of adding simple input-attribute mappings to the library, but I would not like to go inventing my own input naming for such a thing.

So if there is some common class/input used in other libraries for easing the use with flexbox please do let me know. If no such thing exists I think I will go with just documenting the attributes / flex-layout support when I have the time.

**Comment by Bbbrinks** [comment]
I'd say documenting it would be sufficient.

**Comment by sconix** [comment]
I will add the documentation at the latest when doing release which is verified to work withAngular 5 (i.e. 5.0.0).

**Comment by ghost** [comment]
Any news on this?

**Comment by sconix** [comment]
What news are you waiting?

**Comment by ghost** [comment]
@sconix sorry wrong issue. My apologies.

**Comment by sharathdaniel** [comment]
Still not updated this in the documentation. Had to spend a few mins to figure this out.

**Comment by sconix** [comment]
Its in the documentation that scroll area needs a fixed size. The way you do it does not matter, being flex styling or fixed CSS size.
