### ISSUE TITLE
Warning on Chrome: [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event.

### ISSUE THREAD

**Issue by amalfatti** [zefoy/ngx-perfect-scrollbar#79]
Since _Chrome for desktop release 51_, for every Perfect Scrollbar in my template (I use it as directive) i get this warning message in console: 
> `[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

Is it possible to do something to avoid it? Maybe marking the event handler as passive like the warning suggests?

**Comment by sconix** [comment]
Are you sure you are using the latest version of this and perfect-scrollbar? I haven't been getting those warnings for a very long time.

Anyway this is a question for perfect-scrollbar not for this library if you get it with latest version.

**Comment by sconix** [comment]
Actually yeah the warning is still there just haven't been looking the verbose output for a while. There seems to have been issues about that for perfect-scrollbar and the developer has only responded that it will be resolved at some point.

So until that there is nothing you can do other than just ignore it.

**Comment by amalfatti** [comment]
Got it, thanks!
I'll wait for news from perfect-scrollbar developer.

**Comment by salztorte** [comment]
I have the the problem. 
A workaround for development ist set the option "Passive Event Listener Override" to "True (when unspecifed)". You find it in the Chrome://flags.

**Comment by httpete** [comment]
I just installed the latest and I get hundreds of these in Chrome 70

zone.js:1666 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by anovichenko-dbbest** [comment]
Why it was closed? I have the same warnings

**Comment by sconix** [comment]
This is not an issue in this library this is just a wrapper for Perfect Scrollbar. The issue is in Perfect Scrollbar.
