### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by bborad** [zefoy/ngx-perfect-scrollbar#8]
Hi

I am trying to use this in my ng2 app but when I add "PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)" into my NgModule imports it throws below exception. If i remove this from import app works fine.

(index):72 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (localhost:52432/app/app.module.js:23:36)
	    at eval (localhost:52432/app/app.module.js:49:4)
	    at eval (localhost:52432/app/app.module.js:50:3)
	Evaluating localhost:52432/angular2-perfect-scrollbar
	Evaluating localhost:52432/app/app.module.js
	Evaluating localhost:52432/app/main.js
	Error loading localhost:52432/app/main.js
	    at eval (<anonymous>)
	    at Object.eval localhost:52432/app/app.module.js:23:36)
	    at eval (localhost:52432/app/app.module.js:49:4)
	    at eval (localhost:52432/app/app.module.js:50:3)
	Evaluating localhost:52432/angular2-perfect-scrollbar
	Evaluating localhost:52432/app/app.module.js
	Evaluating localhost:52432/app/main.js
	Error loading localhost:52432/app/main.js

Could you please help me identifying the issue. 

Thanks

**Comment by Merraclius** [comment]
It's more looks like your `system.config.js` wrong (or any other bundler config, which you using). 
That error, usually appears, when you try load library, but server don't find it and return just html with first symbol "<". That's why you see `Unexpected token <`.
So you need to check your config file, which import library.
Also, if you want to specify, which library can't loading, try to return `404` error, instead of `404` page from server (only when loading library).

**Comment by bborad** [comment]
But when remove  "PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)" from import list app works fine. so doesn't that mean something is going wrong when importing this module/library?

Below is my system.config.js

`
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'

```
    },
    // map tells the System loader where to look for things
    map: {
        // our app is within the app folder
        app: 'app',
        // angular bundles
        '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
        '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
        '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
        '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
        '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
        '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
        '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
        '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
        // other libraries
        'rxjs': 'npm:rxjs',
        'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
        '@angular/material': 'npm:@angular/material/material.umd.js',
        'angular2-perfect-scrollbar': 'npm:angular2-perfect-scrollbar'

    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
        app: {
            main: './main.js',
            defaultExtension: 'js'
        },
        rxjs: {
            defaultExtension: 'js'
        },
        'angular-in-memory-web-api': {
            main: './index.js',
            defaultExtension: 'js'
        }
    }
});
```

})(this);`

**Comment by Merraclius** [comment]
Main file `index.js` under the folder `lib`. So, with your `map` block, you need to specify path to `index.js` in the `packages` block.
At least for me, it's looks like:

``` javascript
 map: {
        // Other libs
        'angular2-perfect-scrollbar': 'npm:angular2-perfect-scrollbar'
    },
packages: {
        // Other libs
        'angular2-perfect-scrollbar':   { main: 'lib/index.js', defaultExtension: 'js' }
    }
```

And the reason, why everything works, when you remove `PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)` is because application don't try to load library and as result everything works fine

**Comment by bborad** [comment]
yes, needs to set main to 'lib/index.js'

Thanks
