### ISSUE TITLE
OpaqueToken is deprecated

### ISSUE THREAD

**Issue by Eugeny** [zefoy/ngx-perfect-scrollbar#80]
https://github.com/zefoy/ngx-perfect-scrollbar/blob/master/src/lib/perfect-scrollbar.module.ts#L3

Angular team has deprecated it in favor of InjectionToken in Angular 5 beta

**Comment by sconix** [comment]
Yes I am aware, I will make 5.0.0 release once Angular 5 is out of beta.

**Comment by Eugeny** [comment]
Thanks!
