### ISSUE TITLE
Scroll container but not the page

### ISSUE THREAD

**Issue by nicosaliagas** [zefoy/ngx-perfect-scrollbar#81]
Hi,
The scroll works well inside a container but when the scroll goes to the bottom, the page doesn't continue the scroll (same when i want to scroll up a container).
Is it normal ?

thanks

**Comment by sconix** [comment]
Thats called scroll propagation and there are config options to enable that

**Comment by nicosaliagas** [comment]
sorry, yes right thanks 👍 

const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  wheelPropagation: true,
};
