### ISSUE TITLE
Does the scroll bar supports a div that has "height: 100%"?

### ISSUE THREAD

**Issue by komyg** [zefoy/ngx-perfect-scrollbar#82]
Hi,

I am creating an app using Angular 4 and I have a question: does the perfect scroll bar only works if I give a fix height to my div? For example, in my code I have:

```
<perfect-scrollbar [usePSClass]="true" [autoPropagation]="true" [scrollIndicators]="true" class="perfect-scrollbar">
  <div *ngIf="dataReady" class="order-view">
    <!-- Content -->
  </div>
</perfect-scrollbar>
```

And if I put my CSS as:

```
.order-view {
  background-color: $table-background-color;
  padding: 20px 50px;
  position: relative;
  height: 100%;
  width: 100%;
}
```

The scroll bar doesn't work. It doesn't appear. However it works fine if I change my code to:

```
.order-view {
  background-color: $table-background-color;
  padding: 20px 50px;
  position: relative;
  height: 800px;
  width: 100%;
}
```

Thanks,
Felipe

**Comment by sconix** [comment]
If you set height 100% for your content then of course there is nothing to be scrolled. Usually the scrollable content is without height i.e. taking as much space as needed. At least thats the point of scroll area usually that you have content which has height X and when its larger than the height of your scroll container then you get scroll. So not sure why you want to set a height for your scrollable content.

**Comment by komyg** [comment]
Hi, I understand your point.

The thing is that I am creating a software for a point of sale application, which typically uses low resolutions and a touch screen without a keyboard (a good example is the computer terminals that they use in McDonald's to take your order at the counter).

What I wanted to do is to create a vertical scroll bar with two arrow buttons so that the store clerk can scroll the screen up and down without having to use the standard scroll bar which is tiny.

Below is a picture of what I mean: a big table with a big scroll bar beside it. I am not sure if it is possible to achieve this with the Perfect Scroll Bar.

![image](https://user-images.githubusercontent.com/25157901/30428368-b1e2fa06-9929-11e7-9720-8799baa0b6b5.png)

This is why I wanted to make my div with height 100%, because it should occupy the whole screen, but also have a custom scroll bar when needed.

**Comment by sconix** [comment]
You can make the arrows separate elements by positioning with absolute position to be on top / bottom of the perfect scrollbar. So just wrap arrow elements and perfect-scrollbar element inside a div which has relative position. The scrollbar you can always style to be bigger with CSS.

**Comment by komyg** [comment]
Hi,

Thanks for the quick reply! Your suggestion worked very well! And I also managed to change the height of my element using: `height: 80vh;`. This way it always occupies 80% of the available view port.

I have one last question, if that's ok... I saw that you mentioned that I can override the styles and I have been trying to do this, but without success.

Here is my updated code:

```
<div class="order-view">
  <i class="fa fa-2x fa-arrow-circle-up arrow-up-button" aria-hidden="true"></i>
  <perfect-scrollbar [usePSClass]="true" [autoPropagation]="true" [scrollIndicators]="true" class="perfect-scrollbar">
    <div *ngIf="dataReady" class="order-view-table">
       <!-- Content -->
    </div>
  </perfect-scrollbar>
  <i class="fa fa-2x fa-arrow-circle-down arrow-down-button" aria-hidden="true"></i>
</div>
```

And this is what I am trying to do:

```
.order-view {
  height: 80vh;
  width: 100%;
  position: relative;

  .ps__scrollbar-y-rail {
    opacity: 0.6;

    .ps__scrollbar-y {
      width: 20px;
    }
  }

  .arrow-down-button {
    position: absolute;
    bottom: 0;
    right: 0;
    color: $button-color;
    z-index: 100;
  }

  .arrow-up-button {
    position: absolute;
    top: 0;
    right: 0;
    color: $button-color;
    z-index: 100;
  }

  .order-view-table {
    background-color: $table-background-color;
    padding: 20px 50px;
    position: relative;
  }
}
```

I also tried to override the default variables in the perfect [scroll bar css](https://github.com/noraesae/perfect-scrollbar/blob/master/src/css/variables.scss) in my `styles.scss` file:

```
$ps-scrollbar-y-rail-right: 0;
$ps-scrollbar-y-rail-width: 15px;
$ps-scrollbar-y-right: 2px;
$ps-scrollbar-y-width: 20px;
$ps-scrollbar-y-hover-width: 20px;
@import '~perfect-scrollbar/dist/css/perfect-scrollbar.min.css';
```

**Comment by sconix** [comment]
If you are styling withing your components style file then you need to either disable the styles encapsulation or use the :host pseudo selector to style elements that are within a another component.

**Comment by komyg** [comment]
Hi, in the end I managed to solve the problem by turning off the view encapsulation:

CSS:
```
.perfect-scrollbar {
  .ps > .ps__scrollbar-y-rail > .ps__scrollbar-y {
    background-color: red;
    width: 11px;
  }
}
```

TS:
```
@Component({
  selector: 'app-order-view',
  templateUrl: './order-view.component.html',
  styleUrls: ['./order-view.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class OrderViewComponent implements OnInit, OnDestroy {
```

Thank you so much for all the help! :)
