### ISSUE TITLE
Is it possible to add arrow buttons to the beginning and end of the scroll bar?

### ISSUE THREAD

**Issue by komyg** [zefoy/ngx-perfect-scrollbar#83]
Hi,

I am sorry to bother you, but I am creating an app using Angular 4 and I was wondering if it is possible to add arrow buttons to the top and bottom of a scroll bar?

I found [this](https://github.com/noraesae/perfect-scrollbar/issues/331) issue regarding the original perfect scroll bar, but I don't know if I can do the same in Angular.

Thanks,
Komyg

**Comment by sconix** [comment]
I don't see why not. You can always style the scroll bar as you like so using pseudo after / before elements you can add arrows for the scrollbar.
