### ISSUE TITLE
Disabled boolean not switching

### ISSUE THREAD

**Issue by elliotsabitov** [zefoy/ngx-perfect-scrollbar#84]
Hello, and thanks in advance for your time. I am implementing the [disabled] directive and it works however, I want it to be dynamic based on a boolean, and I cannot get it to work. Once disabled becomes true, even if the variable changes back to false, the scrollers stay disabled. I believe that your library needs to re init some PS bindings. Let me know if there is anything I can do to help.

**Comment by sconix** [comment]
The disabled actually disables the perfect-scrollbar library (i.e. unloads it) not the scrollers. So when disabled you might get the normal browser scrollbars depending on your styles. But I haven't tested the disabled property so its also possible that there is a bug so I will check it.

**Comment by elliotsabitov** [comment]
Awesome, that would be great! 

Yeah, I took a look your ngx-perfect-scrollbar (very helpful plugin by the way, thank you) and I saw that disabled was just a boolean that prevented some actions such as Ps.update() from being called. But after debugging, and trying to call the directiveRef.update() or even directiveRef. ngOnInit(), the scrollers would not start working again after being disabled. The interesting part is that if disabled is left to false at first, the scrollbars work, and then when it becomes true, they stop, and turning disabled back to false does not re-init. I am actually thinking now that maybe I can try calling directiveRef.ngOnDestroy() and then directiveRef.ngAfterViewInit() manually after setting disabled back to false. I will try that. I think there is something with PS not being destroyed and reinitialized when toggling the disabled property..

Thank you again for your prompt response and help!

**Comment by sconix** [comment]
By looking at the code I can already tell that there is a bug :) Only the disabling is done and not enabling so I will do a bug fix release on Monday.

**Comment by sconix** [comment]
The disabled property is now fixed in the latest 4.6.3 release.

**Comment by elliotsabitov** [comment]
Oh man so close! It works when initially disabled is set to false, then switching to true and back works fine. However, if disabled flag is set to true initially, the scrolling continues to be disabled and does not turn back on

**Comment by sconix** [comment]
Ah i messed up with the safety checks they should only be checked for hidden changes not for disabled. Will release another fix tomorrow :)

**Comment by sconix** [comment]
I just release 4.6.4 and now it should be fully working :)

**Comment by elliotsabitov** [comment]
Awesome, it worked! Thank you so much!

**Comment by sconix** [comment]
Thanks for reporting this!
