### ISSUE TITLE
Is it possible to check if the scroll bar is visible?

### ISSUE THREAD

**Issue by komyg** [zefoy/ngx-perfect-scrollbar#85]
Hi,

I am sorry to bother you again, but I am trying to find out if the scroll bar is visible or not, so that I can show some arrow buttons that allow the user to scroll up and down my div.

Please note that when I say that the scroll bar is visible, I mean that the contents of my div exceed its size, so the scroll bar appears, otherwise the scroll bar is invisible (everything fits into the div).

I tried to use the properties below, but it seems that their state does not change on the scroll bar visibility.

```
PerfectScrollbarComponent.hidden;
PerfectScrollbarComponent.fxHide;
PerfectScrollbarComponent.fxShow;

PerfectScrollbarComponent.directiveRef.hidden;
PerfectScrollbarComponent.directiveRef.fxHide;
PerfectScrollbarComponent.directiveRef.fxShow;
```

Could you help me?

Thanks once again,
Komyg

**Comment by sconix** [comment]
I don't think there is any ready made api with perfect-scrollbar, but what you can do is to use the geometry function provided by the directive. When you call it normally you get the geometry of the  scroll area and when you call it with true parameter you get the scroll container geometry and then you should be able to check if the scroll container height (h in the geometry object) is bigger than the height of the scroll area.

I think that maybe I should add a helper function for checking this, but at least for now you should be ok with the geometry function.

**Comment by komyg** [comment]
Hi, 

A helper function would be much appreciated. For now I am using the following code: 
```
showScrollButtons(): boolean {
    const scrollGeom = this.scrollComponent.directiveRef.geometry();
    const offsetGeom = this.scrollComponent.directiveRef.geometry('offset');

    if (scrollGeom.h > offsetGeom.h) {
      return true;
    }
    else {
      return false;
    }
  }
```

Thanks for the help!
Komyg

**Comment by sconix** [comment]
I leave this open so I remember add helper function for 5.0.0 release.

**Comment by TrickTrcker** [comment]
Is it possible to visible scrollbar always?

**Comment by sconix** [comment]
Version 4.8.0 will have a scrollable(direction: 'x'|'y'|'any'|'both') helper function.
