### ISSUE TITLE
Use native scroll inside of scroll area

### ISSUE THREAD

**Issue by olaf89** [zefoy/ngx-perfect-scrollbar#87]
I have datatables which are using native scroll, and i cannot change that. I would like to use perfect scroll for the area wrapping my tables, but what i notice is that the native scrolling areas are not working anymore. Is there any way to handle that?

**Comment by sconix** [comment]
I don't quite understand your problem. With that description all I can think of is that there is some style leaking from perfect-scrollbar that effects your datatables, for example overflow style. But since I don't quite get the structure of your app this is just a plain guess.

**Comment by olaf89** [comment]
![image](https://user-images.githubusercontent.com/11535118/30743676-f14a3f8a-9f9e-11e7-9917-e1601702554f.png)

When trying to scroll inside table, perfect scrollbar is activated instead

**Comment by sconix** [comment]
Ok, I am guessing you are talking about mouse wheel? If thats the case maybe you need to capture the wheel events from the datatable and stopPropagation so that they don't reach perfect-scrollbar.

**Comment by olaf89** [comment]
Thanks for suggestion, i tried that but what i don't like that even if there is no scroll, its blocking the outside scroll. Native scroll would scroll inside nested element until its on the bottom, and then scroll the outside one. I don't know if thats best user experience, but something i'm used to as a user. And i could probably do same stuff to detect that and conditionally block scrolling, but its too much in my use case. Anyway thanks again for help.
