### ISSUE TITLE
Can't bind to 'perfectScrollbar'

### ISSUE THREAD

**Issue by munkk** [zefoy/ngx-perfect-scrollbar#88]
hi, i tried to launch examples in ngx-perfect-scrollbar/example folder, and this error has occurred 
![screenshot_6](https://user-images.githubusercontent.com/13670003/30749278-8f60225e-9fbb-11e7-9036-522fa580d209.png)

all npm packages were installed correctly.

**Comment by sconix** [comment]
I think I have forgot to update the library version in the example app package.json. Will fix.

Now the package-lock.json should have uptodate version for the library.
