### ISSUE TITLE
duplicate ps__scrollbar-x-rail and ps__scrollbar-y-rail class

### ISSUE THREAD

**Issue by phongpt156** [zefoy/ngx-perfect-scrollbar#89]
I got this error
![image](https://user-images.githubusercontent.com/21080919/30772557-21214a5c-a088-11e7-8e62-55e3957cd6ea.png)

When i inspect element i found that have 2 ps__scrollbar-x-rail and ps__scrollbar-y-rail in my code 
![image](https://user-images.githubusercontent.com/21080919/30772561-3e873188-a088-11e7-836a-43119673cbbb.png)

Here is my code: 
![image](https://user-images.githubusercontent.com/21080919/30772594-a14cb5e0-a088-11e7-8d33-6b69896bf98d.png)

And my ngx-perfect-scrollbar when i try resize window too

**Comment by sconix** [comment]
Havent seen such thing happening. What is your perfect-scrollbar version and are you using some special config opyions. This smells like perfect-scrollbar problem, but cant be sure. At least would be good to check its issues if something like this is reported.

**Comment by phongpt156** [comment]
I'm using version 4.6.4. U can check my web here: http://mix.net.vn/tim-kiem. I dont have config, i'm using default config

**Comment by Nate93** [comment]
I have the same issue

**Comment by sconix** [comment]
Does it happen on the live demo app as well? If yes then what is your browser. If not then what is your angular version and what is the perfect-scrollbar version (not ngx-perfect-scrollbar, but the perfect-scrollbar which you should have installed under node_modules).

**Comment by sconix** [comment]
For some reason now this is happening to me also so this is most likely due to some package version update. I will investigate and release a fix once I find the reason.

**Comment by sconix** [comment]
This should be now fixed in 4.6.5.
