### ISSUE TITLE
Is it possible to visible scrollbar always?

### ISSUE THREAD

**Issue by TrickTrcker** [zefoy/ngx-perfect-scrollbar#90]
Is it possible to visible scrollbar always?

**Comment by sconix** [comment]
Yes you can override the styles to display them always.

**Comment by komyg** [comment]
See this example: https://github.com/utatti/perfect-scrollbar/blob/master/examples/always-visible.html.

And don't forget to turn off the view encapsulation, otherwise you won't be able to override the styles.

**Comment by sconix** [comment]
For 4.8.2 release I added a helper class to achieve this, so by adding ps-show-always class for the component you get always visible scrollbars.
