### ISSUE TITLE
how to get perfect scroll bar inside aggrid in angular 4

### ISSUE THREAD

**Issue by DigvijaySingh23** [zefoy/ngx-perfect-scrollbar#91]
Hi how i get perfect scroll bar inside the aggrid in angular 4

Code:-
 <perfect-scrollbar class="container" [config]="config" style="height:200px">
            <ag-grid-angular #agGrid style="width: 100%;" class="ag-fresh table-height qualificationTable"  [ngClass]="{'fullScreenTable': fullScreen}" [gridOptions]="gridOptions"
                [columnDefs]="columnDefs" [rowData]="rowData" enableColResize enableSorting enableFilter groupHeaders suppressRowClickSelection
                toolPanelSuppressGroups toolPanelSuppressValues debug rowHeight="42" rowSelection="multiple" (modelUpdated)="onModelUpdated()"
                (cellClicked)="onCellClicked($event)" (cellDoubleClicked)="onCellDoubleClicked($event)" (cellContextMenu)="onCellContextMenu($event)"
                (cellValueChanged)="onCellValueChanged($event)" (cellFocused)="onCellFocused($event)" (rowSelected)="onRowSelected($event)"
                (selectionChanged)="onSelectionChanged()" (beforeFilterChanged)="onBeforeFilterChanged()" (afterFilterChanged)="onAfterFilterChanged()"
                (filterModified)="onFilterModified()" (beforeSortChanged)="onBeforeSortChanged()" (afterSortChanged)="onAfterSortChanged()"
                (virtualRowRemoved)="onVirtualRowRemoved($event)" (rowClicked)="onRowClicked($event)" (gridReady)="onReady($event)"
                (columnEverythingChanged)="onColumnEvent($event)" (columnRowGroupChanged)="onColumnEvent($event)" (columnValueChanged)="onColumnEvent($event)"
                (columnMoved)="onColumnEvent($event)" (columnVisible)="onColumnEvent($event)" (columnGroupOpened)="onColumnEvent($event)"
                (columnResized)="onColumnEvent($event)" (columnPinnedCountChanged)="onColumnEvent($event)">
            </ag-grid-angular>
            </perfect-scrollbar>

**Comment by sconix** [comment]
Wel if ag-grid-angular does not support having a container component then I don't think you can. At least not very easily. Not sure if there is a way to add directive dynamically to a component which I think would be the only option to do that. Of course with totally custom code you can always fetch the right element from the ag-grid-angular component and initialize it manually with perfect-scrollbar library.
