### ISSUE TITLE
when update angular to v5.0.0-rc.0 throw error

### ISSUE THREAD

**Issue by hpyou** [zefoy/ngx-perfect-scrollbar#93]
```
ERROR in node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts (1,31): Module '"node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

**Comment by rdkmaster** [comment]
I'm experiencing the same problem, I'm using Angular 5.0.0-rc.1, and `OpaqueToken` is removed in this version, use `InjectionToken` instead.

**Comment by sconix** [comment]
I have switched to using InjectionToken many versions ago (to be precise 1 month ago) so may I ask how old version of this library you have?

**Comment by hpyou** [comment]
@sconix I used npm package, and the latest version is 4.8.4, which used `OpaqueToken`

**Comment by sconix** [comment]
Ah sorry I forgot that for this library I did not release the InjectionToken change for the 4.x versions. So you can use the next version which is 5.0.0-7 atm. It has the InjectionToken change and all deprecated code removed. I will make the 5.0.0 release as soon as Angular 5 is out so until that you can use the @next version of this library.

**Comment by hpyou** [comment]
@sconix Ok, i know that.

**Comment by rdkmaster** [comment]
Hi @sconix 

we are using angular5.0.0 now, and [this pr](https://github.com/rdkmaster/jigsaw/pull/228) can't be accepted due to this issue, so, can you please release a beta version like 5.0.0-beta of ngx-perfect-scroll to the npm? By doing this, we can finish [this pr](https://github.com/rdkmaster/jigsaw/pull/228) now.

**Comment by sconix** [comment]
Like I said in the previous comment there is a @next release in npm which has been out for sometime now :).

**Comment by hpyou** [comment]
@rdkmaster npm package has the version of 5.0.0-7, you can use npm install ngx-perfect-scrollbar@5.0.0-7 to download
