### ISSUE TITLE
Where is version 5.0.0-9?

### ISSUE THREAD

**Issue by kirilmitev** [zefoy/ngx-perfect-scrollbar#98]
Hey there, I can't seem to install the 5.0.0-9 version, any idea why this might be? 
When I run "npm view ngx-perfect-scrollbar" I get 5.0.0-8 as the latest. How do I install the 5.0.0-9?

Best regards
Kiril

**Comment by sconix** [comment]
There is no such version. Its coming as soon as new release is out from perfect-scrollbar. There was small complication when updating to the latest 1.x version of perfect-scrollbar and I am waiting for a new release which has the changes I need to release 5.0.0-9.

**Comment by kirilmitev** [comment]
First of all, I'm sorry if I sounded demanding or arrogant, I certainly appreciate your efforts!

So just to be sure:
Currently v. 5.0.0-8 as well as v. 4.9.1 do not work with Angular 5 in my Project. Can you confirm this?

**Comment by sconix** [comment]
5.0.0-8 should work with Angular 5 at least I am not aware of any problems, I haven't tested though since I am waiting for flex-layout update to support the Angular 5 which is blocking me to test this lib with our app / example app.

**Comment by kirilmitev** [comment]
Hey Sconix,

perfect-scrollbar: v1.0.3
ngx-perfect-scrollbar: v5.0.0-8
angular: v5 rc.1

could you please take a look at these error messages:
![screenshot1](https://user-images.githubusercontent.com/16428940/31673910-b045c4ca-b360-11e7-8037-a7ba33b14ee3.png)
![screenshot](https://user-images.githubusercontent.com/16428940/31673925-b827fba4-b360-11e7-8bbb-0c46ee96be21.png)


Best regards
Kiril

**Comment by sconix** [comment]
That means that you have wrong perfect-scrollbar version (1.x). Maybe you tried to install the 4.9.x and did not start over when changing version. So make sure that you have perfect-scrollbar 0.8.x.

**Comment by sconix** [comment]
Ah sorry, the latest next release is 5.0.0-7 not 8. The 8 was the buggy release with perfect-scrollbar 1.x. The upcoming -9 release will fix that issue so until that use 5.0.0-7 which is marked as the next release in npm.

So 4.9.0 and 5.0.0-8 were buggy releases for which I have updated the tags in npm to not point to those versions. Upcoming 4.9.2 and 5.0.0-9 will use perfect-scrollbar 1.x and actually work :) Until that 4.8.4 / 5.0.0-7 are the latest fully working versions and they use perfect-scrollbar 0.8.x. Sorry about the hassle, but its bit tricky when you can't remove versions from npm and not release a fix right a way.

**Comment by kirilmitev** [comment]
Thank you very much for your commitment and fast responses! It's working now with v5.0.0-7.
